### PR TITLE
Fixes #2128 Retry the AWS API when looking for a newly created instance

### LINKED ISSUE #2128: Packer fails to find new AWS EC2 Instance
Often packer fails to find a newly created AWS EC2 instance.  Usually the instance is actually created and the API is just being slow to realise it.

Retrying the check to see if the instance has been created would probably fix this.

In our environment, in the previous 28 days packer has failed to find 204 successfully created instances causing us to have to manually mop up the instances, keys and groups.

### PR DESCRIPTION
**Pull request by lokulin**
Sometimes the AWS API responds that it can't find a newly created instance if you poll it too soon after creation.  Retry a few times to be sure it really hasn't been created.

(In our environment, over the past 28 days packer failed to find 204 instances that were successfully created meaning we had to clean up those instances, security groups and keys manually)

### CODE REVIEW

File: builder/amazon/common/step_run_source_instance.go [hunk 1]
```diff
@@ -195,7 +195,16 @@ func (s *StepRunSourceInstance) Run(state multistep.StateBag) multistep.StepActi
...
 	}
 
-	instanceResp, err := ec2conn.Instances([]string{instanceId}, nil)
+	var instanceResp, instanceErr = ec2conn.Instances([]string{instanceId}, nil)
+	for i := 0; i < 10; i++ {
+		if instanceErr == nil {
+			err = instanceErr
+			break
+		}
+		time.Sleep(time.Duration(3))
```
Comment (mitchellh) [inline builder/amazon/common/step_run_source_instance.go]: I think this has time be 3 * time.Second but I'll fix that.

**Comment by mitchellh** [comment]
LGTM. Thanks!
