### PR TITLE
Don't override packer build version with min_packer_version from template

### LINKED ISSUE #2385: Adding "min_packer_version" to packer template crashes 0.8.1
Adding in the new "min_packer_version" key/value (as described at https://packer.io/docs/templates/introduction.html) causes a crash in Packer 0.8.1 (Mac OS X 10.10.4) while attempting to run "packer validate".  Removing "min_packer_version" proceeds as expected with no crash.

```
{
  "builders": [
  ...
  ],
  "description": "Bla bla bla",
  "min_packer_version": "0.8.0",
  "post-processors": [
  ...
  ],
  ...
}
```

Example template that causes the crash:
https://github.com/tylert/packer-build/blob/c93252f25e83743d368bf1d26be995d53c5a13ea/debian/jessie/base-64.json

Contents of crash.log are here:
https://gist.github.com/tylert/41e4dc91acd5640386d3

### PR DESCRIPTION
**Pull request by cbednarski**
- Fixes #2385
- Includes awesome tests

### CODE REVIEW

File: command/meta.go [hunk 1]
```diff
@@ -43,7 +43,6 @@ func (m *Meta) Core(tpl *template.Template) (*packer.Core, error) {
 	config := *m.CoreConfig
 	config.Template = tpl
 	config.Variables = m.flagVars
-	config.Version = m.Version
```
Comment (cbednarski) [inline command/meta.go]: Crash fix
