### PR TITLE
provisioner/chef-client: run cleanup on node [GH-1295]

### LINKED ISSUE #1295: Node/client cleanup never succeeds
chef-client run succeeds, but running the knife node/client delete <NAME> -y always fails with output:

  amazon-instance: Chef Client finished, 0/0 resources updated in 6.707980715 seconds
  ==> amazon-instance: Cleaning up chef node...
  amazon-instance: Response: node 'packer-build-api' not found
  amazon-instance:
  ==> amazon-instance: Terminating the source AWS instance...
  ==> amazon-instance: Deleting temporary security group...
  Build 'amazon-instance' errored: Error cleaning up chef node: exit status 100

Source AMI OS: ubuntu 12.04

packer.json:

```json
{
  "description": "Build AMIs for API",
  "builders": [
    {
      "type": "amazon-instance",
      "ami_description": "Ubuntu64 API Node",
      "bundle_vol_command": "sudo /usr/local/ec2/bin/ec2-bundle-vol -k {{.KeyPath}} -c {{.CertPath}} -u {{.AccountId}} -r {{.Architecture}} -e {{.PrivatePath}}/* -d {{.Destination}} -p {{.Prefix}} --batch --no-filter --exclude /tmp,/mnt,/home/ubuntu/cert",
      "bundle_upload_command": "sudo /usr/local/ec2/bin/ec2-upload-bundle -b {{.BucketName}} -m {{.ManifestPath}} -a {{.AccessKey}} -s {{.SecretKey}} -d {{.BundleDirectory}} --batch --url {{.S3Endpoint}} --retry",

      "access_key": "<REDACTED>",
      "secret_key": "<REDACTED>",

      "source_ami": "<AMI>",
      "instance_type": "m1.small",
      "ssh_username": "ubuntu",
      "ami_virtualization_type": "paravirtual",

      "region": "us-west-2",
      "s3_bucket":"<BUCKET_NAME>",
      "ami_name": "packer api node {{timestamp}}",

      "vpc_id": "<REDACTED>",
      "subnet_id": "<REDACTED>",
      "associate_public_ip_address": true,
      "ssh_private_key_file": "oregon-staging-vpc.pem",

      "account_id": "<REDACTED>",
      "x509_cert_path": "cert.pem",
      "x509_key_path": "key.pem",
      "x509_upload_path": "/home/ubuntu/cert",

      "run_tags": {"Name": "packer build tmp api {{timestamp}}"},
      "tags": {"Name": "packer api node {{timestamp}}"}
    }
  ],
  "provisioners": [
    {
        "type": "shell",
        "remote_path": "/home/ubuntu/packer_prov.sh",
        "inline": ["sudo mkdir /tmp/packer-chef-client", "sudo chmod 777 /tmp/packer-chef-client",
                      "sudo chmod -R 777 /etc/chef", "mkdir -p /home/ubuntu/cert"]
    },
    {
      "type": "chef-client",
      "node_name": "packer-build-api",
      "server_url": "<SERVER_REDACTED>",
      "run_list": [],
      "validation_key_path":"validation.pem",
      "config_template": "chef_server_config.template"
    }
  ]
}
```

Is packer using the -c option for knife when it tries to clean up?

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1295 

This moves the Chef cleanup to run on the server via the `knife` command.

### CODE REVIEW

File: provisioner/chef-client/provisioner.go [hunk 1]
```diff
@@ -352,16 +345,35 @@ func (p *Provisioner) cleanNode(ui packer.Ui, comm packer.Communicator, node str
...
 
-	cmd := exec.Command("sh", "-c", app)
-	out, err := cmd.Output()
+	return nil
+}
 
-	ui.Message(fmt.Sprintf("%s", out))
+func (p *Provisioner) knifeExec(ui packer.Ui, comm packer.Communicator, node string, args []string) error {
+	flags := []string{
+		"-y",
```
Comment (sethvargo) [inline provisioner/chef-client/provisioner.go]: Maybe this is just a @sethvargo-ism, but I prefer to use the long-form here. I think it's clearer about what is being run.

File: provisioner/chef-client/provisioner.go [hunk 2]
```diff
@@ -352,16 +345,35 @@ func (p *Provisioner) cleanNode(ui packer.Ui, comm packer.Communicator, node str
...
+		"-s", fmt.Sprintf("'%s'", p.config.ServerUrl),
```
Comment (sethvargo) [inline provisioner/chef-client/provisioner.go]: Do we need to worry about weird shell-escaping things on Windoze with the single quotes here?

Comment (mitchellh) [inline provisioner/chef-client/provisioner.go]: This Chef provisioner doesn't work on Windows, so no worry.

File: provisioner/chef-client/provisioner.go (hunk 1 above)
Comment (mitchellh) [inline provisioner/chef-client/provisioner.go]: Nah, I think the parameters make it clear. I just don't want to risk breaking it now. :)

File: provisioner/chef-client/provisioner.go [hunk 3]
```diff
@@ -352,16 +345,35 @@ func (p *Provisioner) cleanNode(ui packer.Ui, comm packer.Communicator, node str
...
+	if !p.config.PreventSudo {
+		cmdText = "sudo " + cmdText
+	}
+
+	cmd := &packer.RemoteCmd{Command: cmdText}
+	if err := cmd.StartWithUi(comm, ui); err != nil {
 		return err
 	}
+	if cmd.ExitStatus != 0 {
+		return fmt.Errorf("Non-zero exit status. See output above for more info.")
```
Comment (sethvargo) [inline provisioner/chef-client/provisioner.go]: Can we make this more descriptive? In a long packer run, it might not be intuitive that the `knife client delete` step is what failed. Something like:

```text
Executing {command} failed.
```

Comment (mitchellh) [inline provisioner/chef-client/provisioner.go]: Yep. Doing this now.
