### PR TITLE
provisioner/puppet-masterless: only base if manifest is a file [GH-1933]

### LINKED ISSUE #1933: Masterless puppet provisioner inconsistent behavior
The masterless puppet provisioner was patched to allow manifest_file to be a directory in  https://github.com/mitchellh/packer/pull/1771, however, this introduced another bug which prevented one from applying manifests as a directory. I verified the bug was present as of v0.7.5-73-g6532958.

My provisioner parameters:

    {
      "type": "puppet-masterless",
      "manifest_file": "nubis-puppet/manifests",
      "module_paths": ["nubis-puppet/modules"]
    },

Here's what PACKER_LOG=1 packer build wanted to do:

    2015/01/20 22:07:29 packer-builder-amazon-ebs: 2015/01/20 22:07:29 starting remote command:   sudo -E puppet apply --verbose --modulepath='/tmp/packer-puppet-masterless/module-0' --detailed-exitcodes /tmp/packer-puppet-masterless/manifests/manifests

As you can see the puppet exec command had /manifests appended to my manifest_file path. I dug a bit deeper in the code and decided this was a bug.  filepath.Base() was being called on p.config.ManifestFile which was now allowed to be a directory (around line 323 in puppet-masterless/provisioner.go) and behaving incorrectly:

    manifestFilename := filepath.Base(p.config.ManifestFile)

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1933 

We only want the directory of the manifest file if its a file.

### CODE REVIEW

File: provisioner/puppet-masterless/provisioner.go [hunk 1]
```diff
@@ -259,7 +259,13 @@ func (p *Provisioner) uploadManifests(ui packer.Ui, comm packer.Communicator) (s
 	}
 	defer f.Close()
 
-	manifestFilename := filepath.Base(p.config.ManifestFile)
+	manifestFilename := p.config.ManifestFile
+	if fi, err := os.Stat(p.config.ManifestFile); err != nil {
+		return "", fmt.Errorf("Error inspecting manifest file: %s", err)
+	} else if !fi.IsDir() {
```
Comment (cbednarski) [inline provisioner/puppet-masterless/provisioner.go]: This looks like a bug, but it's actually intentional for BC reasons. Can we add a comment to note that?

Also docs should probably be updated to reflect the same.

Comment (cbednarski) [inline provisioner/puppet-masterless/provisioner.go]: Or If we want to discourage this going forward we could log a warning when we catch the overloaded directory use case. That suffices in place of a comment imo.

Comment (mitchellh) [inline provisioner/puppet-masterless/provisioner.go]: Its not BC, we just support both. I'll update the docs though.

**Comment by mitchellh** [comment]
Ah you're right we support `manifest_dir` as well. I think its best to leave it undocumented, people would just find it by mistake. I'll add a warning.

**Comment by cbednarski** [comment]
LGTM!
