### PR TITLE
OpenStack uses official OpenStack client

### LINKED ISSUE #1472: Crash after openstack SSH timeout
Console log before error was

```
==> openstack: Timeout waiting for SSH.
==> openstack: Terminating the source server...
==> openstack: Deleting temporary keypair...
Build 'openstack' errored: unexpected EOF
```

crash.log ...

```
2014/09/09 14:05:40 Packer Version: 0.6.0  12e28f257f66299e3bb13a053bf06ccd236e7efd
2014/09/09 14:05:40 Packer Target OS/Arch: darwin amd64
2014/09/09 14:05:40 Built with Go Version: go1.2
2014/09/09 14:05:40 Detected home directory from env var: /Users/ross
2014/09/09 14:05:40 Attempting to open config file: /Users/ross/.packerconfig
2014/09/09 14:05:40 File doesn't exist, but doesn't need to. Ignoring.
2014/09/09 14:05:40 Packer config: &{PluginMinPort:0 PluginMaxPort:0 Builders:map[digitalocean:packer-builder-digitalocean null:packer-builder-null amazon-chroot:packer-builder-amazon-chroot docker:packer-builder-docker virtualbox-iso:packer-builder-virtualbox-iso vmware-iso:packer-builder-vmware-iso amazon-ebs:packer-builder-amazon-ebs amazon-instance:packer-builder-amazon-instance googlecompute:packer-builder-googlecompute parallels-iso:packer-builder-parallels-iso parallels-pvm:packer-builder-parallels-pvm openstack:packer-builder-openstack qemu:packer-builder-qemu virtualbox-ovf:packer-builder-virtualbox-ovf vmware-vmx:packer-builder-vmware-vmx] Commands:map[build:packer-command-build fix:packer-command-fix inspect:packer-command-inspect validate:packer-command-validate] PostProcessors:map[vagrant:packer-post-processor-vagrant vsphere:packer-post-processor-vsphere docker-push:packer-post-processor-docker-push docker-import:packer-post-processor-docker-import] Provisioners:map[ansible-local:packer-provisioner-ansible-local chef-client:packer-provisioner-chef-client chef-solo:packer-provisioner-chef-solo file:packer-provisioner-file puppet-masterless:packer-provisioner-puppet-masterless puppet-server:packer-provisioner-puppet-server shell:packer-provisioner-shell salt-masterless:packer-provisioner-salt-masterless]}
2014/09/09 14:05:40 Setting cache directory: /Users/ross/Work/cloudckan/cloudckan/packer/packer_cache
2014/09/09 14:05:40 Environment.Cli: []string{"build", "-var", "openstack_api_key=APIKEY", "-var", "openstack_image_name=DataPress-Solr-2104cb03", "-only", "openstack", "packer-solr.json"}
2014/09/09 14:05:40 command + args: []string{"build", "-var", "openstack_api_key=APIKEY", "-var", "openstack_image_name=DataPress-Solr-2104cb03", "-only", "openstack", "packer-solr.json"}
2014/09/09 14:05:40 Loading command: build
2014/09/09 14:05:40 Creating plugin client for path: /Users/ross/bin/packer-command-build
2014/09/09 14:05:40 Starting plugin: /Users/ross/bin/packer-command-build []string{"/Users/ross/bin/packer-command-build"}
2014/09/09 14:05:40 Waiting for RPC address for: /Users/ross/bin/packer-command-build
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Plugin build against Packer '12e28f257f66299e3bb13a053bf06ccd236e7efd'
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Plugin minimum port: 10000
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Plugin maximum port: 25000
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Plugin address: unix /var/folders/9s/4fdhgfys7_j8wwv7p23t2lkr0000gn/T/packer-plugin358220405
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Waiting for connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Serving a plugin connection...
2014/09/09 14:05:40 Executing command: build
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Reading template: packer-solr.json
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Creating build: openstack
2014/09/09 14:05:40 Loading builder: openstack
2014/09/09 14:05:40 Creating plugin client for path: /Users/ross/bin/packer-builder-openstack
2014/09/09 14:05:40 Starting plugin: /Users/ross/bin/packer-builder-openstack []string{"/Users/ross/bin/packer-builder-openstack"}
2014/09/09 14:05:40 Waiting for RPC address for: /Users/ross/bin/packer-builder-openstack
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 Plugin build against Packer '12e28f257f66299e3bb13a053bf06ccd236e7efd'
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 Plugin minimum port: 10000
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 Plugin maximum port: 25000
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 Plugin address: unix /var/folders/9s/4fdhgfys7_j8wwv7p23t2lkr0000gn/T/packer-plugin508838501
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 Waiting for connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 Serving a plugin connection...
2014/09/09 14:05:40 Loading provisioner: shell
2014/09/09 14:05:40 Creating plugin client for path: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 Starting plugin: /Users/ross/bin/packer-provisioner-shell []string{"/Users/ross/bin/packer-provisioner-shell"}
2014/09/09 14:05:40 Waiting for RPC address for: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin build against Packer '12e28f257f66299e3bb13a053bf06ccd236e7efd'
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin minimum port: 10000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin maximum port: 25000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin address: unix /var/folders/9s/4fdhgfys7_j8wwv7p23t2lkr0000gn/T/packer-plugin294094350
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Waiting for connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Serving a plugin connection...
2014/09/09 14:05:40 Loading provisioner: shell
2014/09/09 14:05:40 Creating plugin client for path: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 Starting plugin: /Users/ross/bin/packer-provisioner-shell []string{"/Users/ross/bin/packer-provisioner-shell"}
2014/09/09 14:05:40 Waiting for RPC address for: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin build against Packer '12e28f257f66299e3bb13a053bf06ccd236e7efd'
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin minimum port: 10000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin maximum port: 25000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin address: unix /var/folders/9s/4fdhgfys7_j8wwv7p23t2lkr0000gn/T/packer-plugin894014625
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Waiting for connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Serving a plugin connection...
2014/09/09 14:05:40 Loading provisioner: shell
2014/09/09 14:05:40 Creating plugin client for path: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 Starting plugin: /Users/ross/bin/packer-provisioner-shell []string{"/Users/ross/bin/packer-provisioner-shell"}
2014/09/09 14:05:40 Waiting for RPC address for: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin build against Packer '12e28f257f66299e3bb13a053bf06ccd236e7efd'
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin minimum port: 10000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin maximum port: 25000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin address: unix /var/folders/9s/4fdhgfys7_j8wwv7p23t2lkr0000gn/T/packer-plugin216119459
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Waiting for connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Serving a plugin connection...
2014/09/09 14:05:40 Loading provisioner: puppet-masterless
2014/09/09 14:05:40 Creating plugin client for path: /Users/ross/bin/packer-provisioner-puppet-masterless
2014/09/09 14:05:40 Starting plugin: /Users/ross/bin/packer-provisioner-puppet-masterless []string{"/Users/ross/bin/packer-provisioner-puppet-masterless"}
2014/09/09 14:05:40 Waiting for RPC address for: /Users/ross/bin/packer-provisioner-puppet-masterless
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-puppet-masterless: 2014/09/09 14:05:40 Plugin build against Packer '12e28f257f66299e3bb13a053bf06ccd236e7efd'
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-puppet-masterless: 2014/09/09 14:05:40 Plugin minimum port: 10000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-puppet-masterless: 2014/09/09 14:05:40 Plugin maximum port: 25000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-puppet-masterless: 2014/09/09 14:05:40 Plugin address: unix /var/folders/9s/4fdhgfys7_j8wwv7p23t2lkr0000gn/T/packer-plugin785524053
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-puppet-masterless: 2014/09/09 14:05:40 Waiting for connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-puppet-masterless: 2014/09/09 14:05:40 Serving a plugin connection...
2014/09/09 14:05:40 Loading provisioner: shell
2014/09/09 14:05:40 Creating plugin client for path: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 Starting plugin: /Users/ross/bin/packer-provisioner-shell []string{"/Users/ross/bin/packer-provisioner-shell"}
2014/09/09 14:05:40 Waiting for RPC address for: /Users/ross/bin/packer-provisioner-shell
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin build against Packer '12e28f257f66299e3bb13a053bf06ccd236e7efd'
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin minimum port: 10000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin maximum port: 25000
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Plugin address: unix /var/folders/9s/4fdhgfys7_j8wwv7p23t2lkr0000gn/T/packer-plugin978297737
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Waiting for connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-provisioner-shell: 2014/09/09 14:05:40 Serving a plugin connection...
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Skipping build 'amazon-ebs' because not specified by -only.
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Skipping build 'vmware-vmx' because not specified by -only.
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Skipping build 'virtualbox-iso' because not specified by -only.
2014/09/09 14:05:40 ui: [1;32mopenstack output will be in this color.[0m
2014/09/09 14:05:40 ui: 
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Build debug mode: false
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Force build: false
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Preparing build: openstack
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 <Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered> <Filtered>{<Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>B<Filtered>u<Filtered>i<Filtered>l<Filtered>d<Filtered>N<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>o<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>B<Filtered>u<Filtered>i<Filtered>l<Filtered>d<Filtered>e<Filtered>r<Filtered>T<Filtered>y<Filtered>p<Filtered>e<Filtered>:<Filtered>o<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>D<Filtered>e<Filtered>b<Filtered>u<Filtered>g<Filtered>:<Filtered>f<Filtered>a<Filtered>l<Filtered>s<Filtered>e<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>F<Filtered>o<Filtered>r<Filtered>c<Filtered>e<Filtered>:<Filtered>f<Filtered>a<Filtered>l<Filtered>s<Filtered>e<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>U<Filtered>s<Filtered>e<Filtered>r<Filtered>V<Filtered>a<Filtered>r<Filtered>s<Filtered>:<Filtered>m<Filtered>a<Filtered>p<Filtered>[<Filtered>a<Filtered>w<Filtered>s<Filtered>_<Filtered>a<Filtered>c<Filtered>c<Filtered>e<Filtered>s<Filtered>s<Filtered>_<Filtered>k<Filtered>e<Filtered>y<Filtered>:<Filtered> <Filtered>a<Filtered>w<Filtered>s<Filtered>_<Filtered>s<Filtered>e<Filtered>c<Filtered>r<Filtered>e<Filtered>t<Filtered>_<Filtered>k<Filtered>e<Filtered>y<Filtered>:<Filtered> <Filtered>o<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered>_<Filtered>a<Filtered>p<Filtered>i<Filtered>_<Filtered>k<Filtered>e<Filtered>y<Filtered>:<Filtered>3<Filtered>c<Filtered>f<Filtered>6<Filtered>5<Filtered>2<Filtered>1<Filtered>8<Filtered>b<Filtered>6<Filtered>a<Filtered>0<Filtered>4<Filtered>6<Filtered>a<Filtered>9<Filtered>8<Filtered>1<Filtered>2<Filtered>2<Filtered>4<Filtered>7<Filtered>f<Filtered>3<Filtered>a<Filtered>5<Filtered>5<Filtered>e<Filtered>f<Filtered>d<Filtered>2<Filtered>5<Filtered> <Filtered>o<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered>_<Filtered>i<Filtered>m<Filtered>a<Filtered>g<Filtered>e<Filtered>_<Filtered>n<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>D<Filtered>a<Filtered>t<Filtered>a<Filtered>P<Filtered>r<Filtered>e<Filtered>s<Filtered>s<Filtered>-<Filtered>S<Filtered>o<Filtered>l<Filtered>r<Filtered>-<Filtered>2<Filtered>1<Filtered>0<Filtered>4<Filtered>c<Filtered>b<Filtered>0<Filtered>3<Filtered>]<Filtered>}<Filtered> <Filtered>A<Filtered>c<Filtered>c<Filtered>e<Filtered>s<Filtered>s<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>U<Filtered>s<Filtered>e<Filtered>r<Filtered>n<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>d<Filtered>a<Filtered>t<Filtered>a<Filtered>p<Filtered>r<Filtered>e<Filtered>s<Filtered>s<Filtered> <Filtered>P<Filtered>a<Filtered>s<Filtered>s<Filtered>w<Filtered>o<Filtered>r<Filtered>d<Filtered>:<Filtered> <Filtered>A<Filtered>p<Filtered>i<Filtered>K<Filtered>e<Filtered>y<Filtered>:<Filtered>3<Filtered>c<Filtered>f<Filtered>6<Filtered>5<Filtered>2<Filtered>1<Filtered>8<Filtered>b<Filtered>6<Filtered>a<Filtered>0<Filtered>4<Filtered>6<Filtered>a<Filtered>9<Filtered>8<Filtered>1<Filtered>2<Filtered>2<Filtered>4<Filtered>7<Filtered>f<Filtered>3<Filtered>a<Filtered>5<Filtered>5<Filtered>e<Filtered>f<Filtered>d<Filtered>2<Filtered>5<Filtered> <Filtered>P<Filtered>r<Filtered>o<Filtered>j<Filtered>e<Filtered>c<Filtered>t<Filtered>:<Filtered> <Filtered>P<Filtered>r<Filtered>o<Filtered>v<Filtered>i<Filtered>d<Filtered>e<Filtered>r<Filtered>:<Filtered>r<Filtered>a<Filtered>c<Filtered>k<Filtered>s<Filtered>p<Filtered>a<Filtered>c<Filtered>e<Filtered>-<Filtered>u<Filtered>k<Filtered> <Filtered>R<Filtered>a<Filtered>w<Filtered>R<Filtered>e<Filtered>g<Filtered>i<Filtered>o<Filtered>n<Filtered>:<Filtered>L<Filtered>O<Filtered>N<Filtered> <Filtered>P<Filtered>r<Filtered>o<Filtered>x<Filtered>y<Filtered>U<Filtered>r<Filtered>l<Filtered>:<Filtered> <Filtered>T<Filtered>e<Filtered>n<Filtered>a<Filtered>n<Filtered>t<Filtered>I<Filtered>d<Filtered>:<Filtered>}<Filtered> <Filtered>I<Filtered>m<Filtered>a<Filtered>g<Filtered>e<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>I<Filtered>m<Filtered>a<Filtered>g<Filtered>e<Filtered>N<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>D<Filtered>a<Filtered>t<Filtered>a<Filtered>P<Filtered>r<Filtered>e<Filtered>s<Filtered>s<Filtered>-<Filtered>S<Filtered>o<Filtered>l<Filtered>r<Filtered>-<Filtered>2<Filtered>1<Filtered>0<Filtered>4<Filtered>c<Filtered>b<Filtered>0<Filtered>3<Filtered>}<Filtered> <Filtered>R<Filtered>u<Filtered>n<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>S<Filtered>o<Filtered>u<Filtered>r<Filtered>c<Filtered>e<Filtered>I<Filtered>m<Filtered>a<Filtered>g<Filtered>e<Filtered>:<Filtered>9<Filtered>2<Filtered>8<Filtered>e<Filtered>7<Filtered>0<Filtered>9<Filtered>d<Filtered>-<Filtered>3<Filtered>5<Filtered>f<Filtered>0<Filtered>-<Filtered>4<Filtered>7<Filtered>e<Filtered>b<Filtered>-<Filtered>b<Filtered>2<Filtered>9<Filtered>6<Filtered>-<Filtered>d<Filtered>1<Filtered>8<Filtered>e<Filtered>1<Filtered>b<Filtered>0<Filtered>a<Filtered>7<Filtered>6<Filtered>b<Filtered>7<Filtered> <Filtered>F<Filtered>l<Filtered>a<Filtered>v<Filtered>o<Filtered>r<Filtered>:<Filtered>p<Filtered>e<Filtered>r<Filtered>f<Filtered>o<Filtered>r<Filtered>m<Filtered>a<Filtered>n<Filtered>c<Filtered>e<Filtered>1<Filtered>-<Filtered>8<Filtered> <Filtered>R<Filtered>a<Filtered>w<Filtered>S<Filtered>S<Filtered>H<Filtered>T<Filtered>i<Filtered>m<Filtered>e<Filtered>o<Filtered>u<Filtered>t<Filtered>:<Filtered>5<Filtered>m<Filtered> <Filtered>S<Filtered>S<Filtered>H<Filtered>U<Filtered>s<Filtered>e<Filtered>r<Filtered>n<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>r<Filtered>o<Filtered>o<Filtered>t<Filtered> <Filtered>S<Filtered>S<Filtered>H<Filtered>P<Filtered>o<Filtered>r<Filtered>t<Filtered>:<Filtered>2<Filtered>2<Filtered> <Filtered>O<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered>P<Filtered>r<Filtered>o<Filtered>v<Filtered>i<Filtered>d<Filtered>e<Filtered>r<Filtered>:<Filtered>r<Filtered>a<Filtered>c<Filtered>k<Filtered>s<Filtered>p<Filtered>a<Filtered>c<Filtered>e<Filtered> <Filtered>U<Filtered>s<Filtered>e<Filtered>F<Filtered>l<Filtered>o<Filtered>a<Filtered>t<Filtered>i<Filtered>n<Filtered>g<Filtered>I<Filtered>p<Filtered>:<Filtered>f<Filtered>a<Filtered>l<Filtered>s<Filtered>e<Filtered> <Filtered>F<Filtered>l<Filtered>o<Filtered>a<Filtered>t<Filtered>i<Filtered>n<Filtered>g<Filtered>I<Filtered>p<Filtered>P<Filtered>o<Filtered>o<Filtered>l<Filtered>:<Filtered> <Filtered>F<Filtered>l<Filtered>o<Filtered>a<Filtered>t<Filtered>i<Filtered>n<Filtered>g<Filtered>I<Filtered>p<Filtered>:<Filtered> <Filtered>S<Filtered>e<Filtered>c<Filtered>u<Filtered>r<Filtered>i<Filtered>t<Filtered>y<Filtered>G<Filtered>r<Filtered>o<Filtered>u<Filtered>p<Filtered>s<Filtered>:<Filtered>[<Filtered>]<Filtered> <Filtered>s<Filtered>s<Filtered>h<Filtered>T<Filtered>i<Filtered>m<Filtered>e<Filtered>o<Filtered>u<Filtered>t<Filtered>:<Filtered>3<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>}<Filtered> <Filtered>t<Filtered>p<Filtered>l<Filtered>:<Filtered>0<Filtered>x<Filtered>c<Filtered>2<Filtered>1<Filtered>0<Filtered>0<Filtered>d<Filtered>9<Filtered>b<Filtered>4<Filtered>0<Filtered>}<Filtered>
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Waiting on builds to complete...
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Starting build run: openstack
2014/09/09 14:05:40 /Users/ross/bin/packer-command-build: 2014/09/09 14:05:40 Running builder: openstack
2014/09/09 14:05:40 ui: [1;32m==> openstack: Creating temporary keypair for this instance...[0m
2014/09/09 14:05:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:40 temporary keypair name: packer 540efb24-3579-e233-5f77-92920c908139
2014/09/09 14:05:49 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:49 server id: 5b9ed179-1007-4740-b04c-f6148d2563dd
2014/09/09 14:05:49 ui: [1;32m==> openstack: Waiting for server (5b9ed179-1007-4740-b04c-f6148d2563dd) to become ready...[0m
2014/09/09 14:05:49 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:49 Waiting for state to become: ACTIVE
2014/09/09 14:05:49 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:49 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:05:52 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:52 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:05:54 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:54 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:05:56 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:56 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:05:59 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:05:59 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:01 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:01 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:03 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:03 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:06 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:06 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:09 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:09 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:11 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:11 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:14 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:14 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:16 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:16 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:19 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:19 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:21 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:21 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:24 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:24 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/09/09 14:06:26 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:26 Waiting for state to become: ACTIVE currently BUILD (40%)
2014/09/09 14:06:28 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:28 Waiting for state to become: ACTIVE currently BUILD (50%)
2014/09/09 14:06:30 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:30 Waiting for state to become: ACTIVE currently BUILD (50%)
2014/09/09 14:06:32 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:32 Waiting for state to become: ACTIVE currently BUILD (70%)
2014/09/09 14:06:35 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:35 Waiting for state to become: ACTIVE currently BUILD (70%)
2014/09/09 14:06:37 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:37 Waiting for state to become: ACTIVE currently BUILD (80%)
2014/09/09 14:06:39 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:39 Waiting for state to become: ACTIVE currently BUILD (80%)
2014/09/09 14:06:41 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:41 Waiting for state to become: ACTIVE currently BUILD (80%)
2014/09/09 14:06:43 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:43 Waiting for state to become: ACTIVE currently BUILD (80%)
2014/09/09 14:06:46 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:46 Waiting for state to become: ACTIVE currently BUILD (80%)
2014/09/09 14:06:49 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:49 Waiting for state to become: ACTIVE currently BUILD (80%)
2014/09/09 14:06:51 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:51 Waiting for SSH, up to timeout: 5m0s
2014/09/09 14:06:51 ui: [1;32m==> openstack: Waiting for SSH to become available...[0m
2014/09/09 14:06:56 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:06:56 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:01 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:01 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:07 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:07 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:12 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:12 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:17 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:17 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:22 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:22 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:27 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:27 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:32 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:32 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:37 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:37 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:42 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:42 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:48 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:48 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:53 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:53 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:07:58 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:07:58 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:03 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:03 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:08 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:08 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:13 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:13 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:18 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:18 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:23 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:23 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:29 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:29 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:34 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:34 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:39 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:39 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:44 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:44 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:49 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:49 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:54 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:54 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:08:59 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:08:59 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:04 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:04 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:09 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:09 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:15 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:15 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:20 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:20 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:25 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:25 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:30 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:30 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:35 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:35 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:40 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:40 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:45 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:45 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:50 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:50 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:09:56 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:09:56 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:01 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:01 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:06 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:06 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:11 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:11 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:16 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:16 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:21 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:21 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:26 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:26 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:31 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:31 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:36 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:36 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:42 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:42 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:47 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:47 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:52 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:52 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:10:57 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:10:57 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:02 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:02 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:07 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:07 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:12 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:12 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:17 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:17 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:23 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:23 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:28 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:28 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:33 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:33 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:38 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:38 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:43 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:43 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:48 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:48 TCP connection to SSH ip/port failed: dial tcp: too many colons in address 2a00:1a48:7808:102:8b0d:b745:d418:79a8:22
2014/09/09 14:11:51 ui error: [1;31m==> openstack: Timeout waiting for SSH.[0m
2014/09/09 14:11:51 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:51 SSH wait cancelled. Exiting loop.
2014/09/09 14:11:51 ui: [1;32m==> openstack: Terminating the source server...[0m
2014/09/09 14:11:54 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:54 Waiting for state to become: DELETED
2014/09/09 14:11:54 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:54 Waiting for state to become: DELETED currently ACTIVE (0%)
2014/09/09 14:11:56 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:56 Waiting for state to become: DELETED currently ACTIVE (0%)
2014/09/09 14:11:59 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:11:59 Waiting for state to become: DELETED currently ACTIVE (0%)
2014/09/09 14:12:01 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:12:01 Waiting for state to become: DELETED currently ACTIVE (0%)
2014/09/09 14:12:05 /Users/ross/bin/packer-builder-openstack: 2014/09/09 14:12:05 Waiting for state to become: DELETED currently ACTIVE (0%)
2014/09/09 14:12:08 ui: [1;32m==> openstack: Deleting temporary keypair...[0m
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: panic: runtime error: invalid memory address or nil pointer dereference
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: [signal 0xb code=0x1 addr=0x198 pc=0x533b0]
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 24 [running]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: runtime.panic(0x392c40, 0x876c99)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/runtime/panic.c:266 +0xb6
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/rackspace/gophercloud.(*genericServersProvider).ServerById(0xc2101c5420, 0xc210481240, 0x24, 0x87b6e0, 0x874680, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/rackspace/gophercloud/servers.go:100 +0xd0
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.func·001(0x77359400, 0x33, 0xde15d0, 0x3, 0x3, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/server.go:36 +0x5a
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.WaitForState(0xc210267b80, 0x36ec80, 0xc2103b71c0, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/server.go:54 +0x13a
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.(*StepRunSourceServer).Cleanup(0xc21020f7d0, 0xb223d8, 0xc2101c5450)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/step_run_source_server.go:93 +0x383
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/multistep.(*BasicRunner).Run(0xc210267380, 0xb223d8, 0xc2101c5450)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/multistep/basic_runner.go:82 +0x30e
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.(*Builder).Run(0xc2100ac000, 0xb13398, 0xc2100e50c0, 0xb133e0, 0xc2100e6020, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/builder.go:119 +0xab8
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc210071e60, 0x1, 0xc210000a78, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x28b
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: reflect.Value.call(0x358020, 0x3b70f0, 0x130, 0x40e8c0, 0x4, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/reflect/value.go:474 +0xe0b
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: reflect.Value.Call(0x358020, 0x3b70f0, 0x130, 0xde1ee8, 0x3, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/reflect/value.go:345 +0x9d
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net/rpc.(*service).call(0xc210055a80, 0xc210055a40, 0xc210000498, 0xc210060b80, 0xc2100499c0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/rpc/server.go:381 +0x159
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by net/rpc.(*Server).ServeCodec
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/rpc/server.go:452 +0x3bb
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 1 [semacquire]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: sync.runtime_Syncsemacquire(0xc21006f280)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/runtime/sema.goc:257 +0xca
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: sync.(*Cond).Wait(0xc21006f270)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/sync/cond.go:62 +0x89
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: io.(*pipe).read(0xc21006f240, 0xc2100cc000, 0x1000, 0x1000, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/io/pipe.go:52 +0x245
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: io.(*PipeReader).Read(0xc210000480, 0xc2100cc000, 0x1000, 0x1000, 0x21, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/io/pipe.go:134 +0x5f
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*Stream).Read(0xc21004d600, 0xc2100cc000, 0x1000, 0x1000, 0x2113ef, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:549 +0x53
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: bufio.(*Reader).fill(0xc21004d060)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/bufio/bufio.go:91 +0x110
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: bufio.(*Reader).ReadByte(0xc21004d060, 0x82, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/bufio/bufio.go:183 +0x7f
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*ioDecReader).readn1(0xc2100920f0, 0x16)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/decode.go:90 +0x37
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*msgpackDecDriver).initReadNext(0xc210071ee0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/msgpack.go:540 +0x3e
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*Decoder).decode(0xc21004d660, 0x2ca5e0, 0xc210071f00)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/decode.go:635 +0x3b
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*Decoder).Decode(0xc21004d660, 0x2ca5e0, 0xc210071f00, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/decode.go:630 +0x69
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*rpcCodec).read(0xc210055ac0, 0x2ca5e0, 0xc210071f00, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/rpc.go:88 +0xcc
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*goRpcCodec).ReadRequestHeader(0xc210055ac0, 0xc210071f00, 0xc115, 0xc21008d000)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/rpc.go:127 +0x42
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net/rpc.(*Server).readRequestHeader(0xc210055a40, 0xb12cb8, 0xc210055ac0, 0x0, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/rpc/server.go:551 +0x9b
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net/rpc.(*Server).readRequest(0xc210055a40, 0xb12cb8, 0xc210055ac0, 0xc210060b80, 0xc2100499c0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/rpc/server.go:518 +0xa0
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net/rpc.(*Server).ServeCodec(0xc210055a40, 0xb12cb8, 0xc210055ac0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/rpc/server.go:437 +0x66
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*Server).Serve(0xc210071e40)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/server.go:151 +0x1cf
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: main.main()
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/plugin/builder-openstack/main.go:14 +0xb1
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 3 [syscall]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: os/signal.loop()
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by os/signal.init·1
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/os/signal/signal_unix.go:27 +0x31
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 5 [chan receive]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/plugin.func·023()
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:95 +0x59
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by github.com/mitchellh/packer/packer/plugin.Server
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:99 +0xaf3
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 6 [select]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*MuxConn).cleaner(0xc2100797e0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:222 +0x3d8
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by github.com/mitchellh/packer/packer/rpc.NewMuxConn
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:71 +0xdd
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 7 [runnable]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: syscall.Syscall(0x3, 0x5, 0xc2101e0fa0, 0x4, 0x4, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/syscall/asm_darwin_amd64.s:36 +0x61
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: syscall.read(0x5, 0xc2101e0fa0, 0x4, 0x8, 0x72, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/syscall/zsyscall_darwin_amd64.go:900 +0x72
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: syscall.Read(0x5, 0xc2101e0fa0, 0x4, 0x8, 0x36b120, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/syscall/syscall_unix.go:135 +0x5c
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net.(*netFD).Read(0xc210079690, 0xc2101e0fa0, 0x4, 0x8, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/fd_unix.go:200 +0x1eb
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net.(*conn).Read(0xc210000468, 0xc2101e0fa0, 0x4, 0x8, 0x8, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/net.go:122 +0xc5
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: io.ReadAtLeast(0xb12830, 0xc210000468, 0xc2101e0fa0, 0x4, 0x8, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/io/io.go:288 +0xf6
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: io.ReadFull(0xb12830, 0xc210000468, 0xc2101e0fa0, 0x4, 0x8, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/io/io.go:306 +0x71
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: encoding/binary.Read(0xb12830, 0xc210000468, 0xb12858, 0xc210000468, 0x2cfd20, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/encoding/binary/binary.go:146 +0x103
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*MuxConn).loop(0xc2100797e0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:274 +0x321
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by github.com/mitchellh/packer/packer/rpc.NewMuxConn
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:72 +0xf4
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 9 [chan receive]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.func·005()
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:508 +0x64
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by github.com/mitchellh/packer/packer/rpc.newStream
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:525 +0x169
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 38 [select]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net/http.(*persistConn).writeLoop(0xc2100e1980)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/http/transport.go:791 +0x271
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by net/http.(*Transport).dialConn
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/http/transport.go:529 +0x61e
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 25 [chan receive]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.func·005()
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:508 +0x64
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by github.com/mitchellh/packer/packer/rpc.newStream
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:525 +0x169
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 26 [semacquire]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: sync.runtime_Syncsemacquire(0xc21006f400)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/runtime/sema.goc:257 +0xca
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: sync.(*Cond).Wait(0xc21006f3f0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/sync/cond.go:62 +0x89
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: io.(*pipe).read(0xc21006f3c0, 0xc210117000, 0x1000, 0x1000, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/io/pipe.go:52 +0x245
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: io.(*PipeReader).Read(0xc210000a88, 0xc210117000, 0x1000, 0x1000, 0x10, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/io/pipe.go:134 +0x5f
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*Stream).Read(0xc21004dea0, 0xc210117000, 0x1000, 0x1000, 0x210f34, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/muxconn.go:549 +0x53
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: bufio.(*Reader).fill(0xc21004d2a0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/bufio/bufio.go:91 +0x110
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: bufio.(*Reader).ReadByte(0xc21004d2a0, 0x1a17cb8, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/bufio/bufio.go:183 +0x7f
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*ioDecReader).readn1(0xc2100c8300, 0x16)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/decode.go:90 +0x37
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*msgpackDecDriver).initReadNext(0xc2100e5080)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/msgpack.go:540 +0x3e
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*Decoder).decode(0xc210118000, 0x2ca620, 0xc2100fb2a0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/decode.go:635 +0x3b
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*Decoder).Decode(0xc210118000, 0x2ca620, 0xc2100fb2a0, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/decode.go:630 +0x69
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*rpcCodec).read(0xc210119000, 0x2ca620, 0xc2100fb2a0, 0x0, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/rpc.go:88 +0xcc
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: github.com/ugorji/go/codec.(*goRpcCodec).ReadResponseHeader(0xc210119000, 0xc2100fb2a0, 0xc210336370, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/ugorji/go/codec/rpc.go:123 +0x42
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net/rpc.(*Client).input(0xc210118060)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/rpc/client.go:107 +0xbf
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by net/rpc.NewClientWithCodec
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/rpc/client.go:199 +0x91
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 28 [syscall]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: runtime.goexit()
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/runtime/proc.c:1394
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: goroutine 37 [IO wait]:
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net.runtime_pollWait(0xb12578, 0x72, 0x0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/runtime/netpoll.goc:116 +0x6a
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net.(*pollDesc).Wait(0xc210425370, 0x72, 0xb10f60, 0x23)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net.(*pollDesc).WaitRead(0xc210425370, 0x23, 0xb10f60)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net.(*netFD).Read(0xc210425310, 0xc210115800, 0x800, 0x800, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/fd_unix.go:204 +0x2a0
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net.(*conn).Read(0xc21026f1b0, 0xc210115800, 0x800, 0x800, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/net.go:122 +0xc5
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: crypto/tls.(*block).readFromUntil(0xc2102704e0, 0xb136d0, 0xc21026f1b0, 0x5, 0xc21026f1b0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/crypto/tls/conn.go:459 +0xb6
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: crypto/tls.(*Conn).readRecord(0xc21005a500, 0x17, 0x0, 0x8)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/crypto/tls/conn.go:539 +0x107
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: crypto/tls.(*Conn).Read(0xc21005a500, 0xc210575000, 0x1000, 0x1000, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/crypto/tls/conn.go:897 +0x135
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: bufio.(*Reader).fill(0xc2104226c0)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/bufio/bufio.go:91 +0x110
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: bufio.(*Reader).Peek(0xc2104226c0, 0x1, 0x0, 0x0, 0x0, ...)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/bufio/bufio.go:119 +0xcb
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: net/http.(*persistConn).readLoop(0xc2100e1980)
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/http/transport.go:687 +0xb7
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: created by net/http.(*Transport).dialConn
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: 	/Users/mitchellh/go/src/pkg/net/http/transport.go:528 +0x607
2014/09/09 14:12:09 [ERR] Error reading stream direction: EOF
2014/09/09 14:12:09 [INFO] Mux connection loop exiting
2014/09/09 14:12:09 /Users/ross/bin/packer-builder-openstack: plugin process exited
2014/09/09 14:12:09 ui error: [1;31mBuild 'openstack' errored: unexpected EOF[0m
2014/09/09 14:12:09 /Users/ross/bin/packer-command-build: 2014/09/09 14:12:09 Builds completed. Waiting on interrupt barrier...
2014/09/09 14:12:09 machine readable: error-count []string{"1"}
2014/09/09 14:12:09 ui error: 
==> Some builds didn't complete successfully and had errors:
2014/09/09 14:12:09 machine readable: openstack,error []string{"unexpected EOF"}
2014/09/09 14:12:09 ui error: --> openstack: unexpected EOF
2014/09/09 14:12:09 ui: 
==> Builds finished but no artifacts were created.
2014/09/09 14:12:09 waiting for all plugin processes to complete...
2014/09/09 14:12:09 [ERR] Error reading stream direction: EOF
2014/09/09 14:12:09 [INFO] Mux connection loop exiting
2014/09/09 14:12:09 /Users/ross/bin/packer-provisioner-puppet-masterless: plugin process exited
2014/09/09 14:12:09 [ERR] Error reading stream direction: EOF
2014/09/09 14:12:09 [INFO] Mux connection loop exiting
2014/09/09 14:12:09 /Users/ross/bin/packer-command-build: plugin process exited
2014/09/09 14:12:09 [ERR] Error reading stream direction: EOF
2014/09/09 14:12:09 [INFO] Mux connection loop exiting
2014/09/09 14:12:09 [ERR] Error reading stream direction: EOF
2014/09/09 14:12:09 [INFO] Mux connection loop exiting
2014/09/09 14:12:09 [ERR] Error reading stream direction: EOF
2014/09/09 14:12:09 [INFO] Mux connection loop exiting
2014/09/09 14:12:09 /Users/ross/bin/packer-provisioner-shell: plugin process exited
2014/09/09 14:12:09 [ERR] Error reading stream direction: EOF
2014/09/09 14:12:09 [INFO] Mux connection loop exiting
2014/09/09 14:12:09 /Users/ross/bin/packer-provisioner-shell: plugin process exited
2014/09/09 14:12:09 /Users/ross/bin/packer-provisioner-shell: plugin process exited
2014/09/09 14:12:09 /Users/ross/bin/packer-provisioner-shell: plugin process exited
```

### LINKED ISSUE #1626: Upgrade to latest GopherCloud API
This will likely fix a lot of bugs since we're pinned at a super old (July 2014) version right now. But we're going to remain pinned until we can figure out the upgrade process.

### LINKED ISSUE #1785: openstack builder raises "Build 'openstack' errored: unexpected EOF" when deleting temporary keypiar
I tried the following build and got an error "Build 'openstack' errored: unexpected EOF".
This error occurs every time.
It seems to occur when deleting temporary keypair.
Image creation is done correctly each time.

```
{
  "variables": {},
  "builders": [
    { 
      "type": "openstack",
      "source_image": "90d8d31c-6386-4740-8ae5-e8a80b8fc6dd",
      "image_name": "httpd-installed",
      "flavor": "2",
      "networks": [
        "4aef0f35-87b5-4d87-9000-d3ca6f0769d7"
      ],
      "ssh_username": "root",
      "use_floating_ip": "true",
      "floating_ip": "192.168.100.211"
    }
  ],
  "provisioners": [
    { 
      "type": "shell",
      "inline": [
        "sleep 30",
        "yum install -y httpd",
        "rm -f /etc/udev/rules.d/70-persistent-net.rules"
      ]
    }
  ]
}
```

crash log are following.

```
2014/12/19 16:16:10 [INFO] Packer version: 0.7.5  9cd66feeacbd9cb318b72eb5ed59428c5b8c37ac+CHANGES
2014/12/19 16:16:10 Packer Target OS/Arch: linux amd64
2014/12/19 16:16:10 Built with Go Version: go1.3.3
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: amazon-chroot = /home/vagrant/packer/packer-builder-amazon-chroot
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: amazon-ebs = /home/vagrant/packer/packer-builder-amazon-ebs
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: amazon-instance = /home/vagrant/packer/packer-builder-amazon-instance
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: digitalocean = /home/vagrant/packer/packer-builder-digitalocean
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker = /home/vagrant/packer/packer-builder-docker
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: googlecompute = /home/vagrant/packer/packer-builder-googlecompute
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: null = /home/vagrant/packer/packer-builder-null
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: openstack = /home/vagrant/packer/packer-builder-openstack
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: parallels-iso = /home/vagrant/packer/packer-builder-parallels-iso
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: parallels-pvm = /home/vagrant/packer/packer-builder-parallels-pvm
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: qemu = /home/vagrant/packer/packer-builder-qemu
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: virtualbox-iso = /home/vagrant/packer/packer-builder-virtualbox-iso
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: virtualbox-ovf = /home/vagrant/packer/packer-builder-virtualbox-ovf
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vmware-iso = /home/vagrant/packer/packer-builder-vmware-iso
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vmware-vmx = /home/vagrant/packer/packer-builder-vmware-vmx
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: atlas = /home/vagrant/packer/packer-post-processor-atlas
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: compress = /home/vagrant/packer/packer-post-processor-compress
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-import = /home/vagrant/packer/packer-post-processor-docker-import
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-push = /home/vagrant/packer/packer-post-processor-docker-push
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-save = /home/vagrant/packer/packer-post-processor-docker-save
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-tag = /home/vagrant/packer/packer-post-processor-docker-tag
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vagrant = /home/vagrant/packer/packer-post-processor-vagrant
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vagrant-cloud = /home/vagrant/packer/packer-post-processor-vagrant-cloud
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vsphere = /home/vagrant/packer/packer-post-processor-vsphere
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: ansible-local = /home/vagrant/packer/packer-provisioner-ansible-local
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: chef-client = /home/vagrant/packer/packer-provisioner-chef-client
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: chef-solo = /home/vagrant/packer/packer-provisioner-chef-solo
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: file = /home/vagrant/packer/packer-provisioner-file
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: puppet-masterless = /home/vagrant/packer/packer-provisioner-puppet-masterless
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: puppet-server = /home/vagrant/packer/packer-provisioner-puppet-server
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: salt-masterless = /home/vagrant/packer/packer-provisioner-salt-masterless
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: shell = /home/vagrant/packer/packer-provisioner-shell
2014/12/19 16:16:10 Detected home directory from env var: /home/vagrant
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: amazon-chroot = /home/vagrant/packer/packer-builder-amazon-chroot
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: amazon-ebs = /home/vagrant/packer/packer-builder-amazon-ebs
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: amazon-instance = /home/vagrant/packer/packer-builder-amazon-instance
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: digitalocean = /home/vagrant/packer/packer-builder-digitalocean
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker = /home/vagrant/packer/packer-builder-docker
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: googlecompute = /home/vagrant/packer/packer-builder-googlecompute
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: null = /home/vagrant/packer/packer-builder-null
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: openstack = /home/vagrant/packer/packer-builder-openstack
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: parallels-iso = /home/vagrant/packer/packer-builder-parallels-iso
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: parallels-pvm = /home/vagrant/packer/packer-builder-parallels-pvm
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: qemu = /home/vagrant/packer/packer-builder-qemu
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: virtualbox-iso = /home/vagrant/packer/packer-builder-virtualbox-iso
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: virtualbox-ovf = /home/vagrant/packer/packer-builder-virtualbox-ovf
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vmware-iso = /home/vagrant/packer/packer-builder-vmware-iso
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vmware-vmx = /home/vagrant/packer/packer-builder-vmware-vmx
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: atlas = /home/vagrant/packer/packer-post-processor-atlas
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: compress = /home/vagrant/packer/packer-post-processor-compress
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-import = /home/vagrant/packer/packer-post-processor-docker-import
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-push = /home/vagrant/packer/packer-post-processor-docker-push
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-save = /home/vagrant/packer/packer-post-processor-docker-save
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: docker-tag = /home/vagrant/packer/packer-post-processor-docker-tag
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vagrant = /home/vagrant/packer/packer-post-processor-vagrant
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vagrant-cloud = /home/vagrant/packer/packer-post-processor-vagrant-cloud
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: vsphere = /home/vagrant/packer/packer-post-processor-vsphere
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: ansible-local = /home/vagrant/packer/packer-provisioner-ansible-local
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: chef-client = /home/vagrant/packer/packer-provisioner-chef-client
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: chef-solo = /home/vagrant/packer/packer-provisioner-chef-solo
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: file = /home/vagrant/packer/packer-provisioner-file
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: puppet-masterless = /home/vagrant/packer/packer-provisioner-puppet-masterless
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: puppet-server = /home/vagrant/packer/packer-provisioner-puppet-server
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: salt-masterless = /home/vagrant/packer/packer-provisioner-salt-masterless
2014/12/19 16:16:10 [DEBUG] Discoverd plugin: shell = /home/vagrant/packer/packer-provisioner-shell
2014/12/19 16:16:10 Detected home directory from env var: /home/vagrant
2014/12/19 16:16:10 Attempting to open config file: /home/vagrant/.packerconfig
2014/12/19 16:16:10 File doesn't exist, but doesn't need to. Ignoring.
2014/12/19 16:16:10 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[docker:/home/vagrant/packer/packer-builder-docker googlecompute:/home/vagrant/packer/packer-builder-googlecompute openstack:/home/vagrant/packer/packer-builder-openstack parallels-iso:/home/vagrant/packer/packer-builder-parallels-iso parallels-pvm:/home/vagrant/packer/packer-builder-parallels-pvm qemu:/home/vagrant/packer/packer-builder-qemu amazon-chroot:/home/vagrant/packer/packer-builder-amazon-chroot amazon-instance:/home/vagrant/packer/packer-builder-amazon-instance vmware-iso:/home/vagrant/packer/packer-builder-vmware-iso virtualbox-iso:/home/vagrant/packer/packer-builder-virtualbox-iso virtualbox-ovf:/home/vagrant/packer/packer-builder-virtualbox-ovf amazon-ebs:/home/vagrant/packer/packer-builder-amazon-ebs null:/home/vagrant/packer/packer-builder-null digitalocean:/home/vagrant/packer/packer-builder-digitalocean vmware-vmx:/home/vagrant/packer/packer-builder-vmware-vmx] PostProcessors:map[compress:/home/vagrant/packer/packer-post-processor-compress docker-import:/home/vagrant/packer/packer-post-processor-docker-import docker-save:/home/vagrant/packer/packer-post-processor-docker-save atlas:/home/vagrant/packer/packer-post-processor-atlas docker-push:/home/vagrant/packer/packer-post-processor-docker-push docker-tag:/home/vagrant/packer/packer-post-processor-docker-tag vagrant:/home/vagrant/packer/packer-post-processor-vagrant vagrant-cloud:/home/vagrant/packer/packer-post-processor-vagrant-cloud vsphere:/home/vagrant/packer/packer-post-processor-vsphere] Provisioners:map[chef-client:/home/vagrant/packer/packer-provisioner-chef-client chef-solo:/home/vagrant/packer/packer-provisioner-chef-solo file:/home/vagrant/packer/packer-provisioner-file puppet-masterless:/home/vagrant/packer/packer-provisioner-puppet-masterless puppet-server:/home/vagrant/packer/packer-provisioner-puppet-server salt-masterless:/home/vagrant/packer/packer-provisioner-salt-masterless shell:/home/vagrant/packer/packer-provisioner-shell ansible-local:/home/vagrant/packer/packer-provisioner-ansible-local]}
2014/12/19 16:16:10 Setting cache directory: /home/vagrant/packer/packer_cache
2014/12/19 16:16:10 Reading template: templates/yum-update.json
2014/12/19 16:16:10 Detected home directory from env var: /home/vagrant
2014/12/19 16:16:10 Creating build: openstack
2014/12/19 16:16:10 Loading builder: openstack
2014/12/19 16:16:10 Creating plugin client for path: /home/vagrant/packer/packer-builder-openstack
2014/12/19 16:16:10 Starting plugin: /home/vagrant/packer/packer-builder-openstack []string{"/home/vagrant/packer/packer-builder-openstack"}
2014/12/19 16:16:10 Waiting for RPC address for: /home/vagrant/packer/packer-builder-openstack
2014/12/19 16:16:10 packer-builder-openstack: 2014/12/19 16:16:10 Plugin minimum port: 10000
2014/12/19 16:16:10 packer-builder-openstack: 2014/12/19 16:16:10 Plugin maximum port: 25000
2014/12/19 16:16:10 packer-builder-openstack: 2014/12/19 16:16:10 Plugin address: unix /tmp/packer-plugin121674227
2014/12/19 16:16:10 packer-builder-openstack: 2014/12/19 16:16:10 Waiting for connection...
2014/12/19 16:16:10 packer-builder-openstack: 2014/12/19 16:16:10 Serving a plugin connection...
2014/12/19 16:16:10 Loading provisioner: shell
2014/12/19 16:16:10 Creating plugin client for path: /home/vagrant/packer/packer-provisioner-shell
2014/12/19 16:16:10 Starting plugin: /home/vagrant/packer/packer-provisioner-shell []string{"/home/vagrant/packer/packer-provisioner-shell"}
2014/12/19 16:16:10 Waiting for RPC address for: /home/vagrant/packer/packer-provisioner-shell
2014/12/19 16:16:10 packer-provisioner-shell: 2014/12/19 16:16:10 Plugin minimum port: 10000
2014/12/19 16:16:10 packer-provisioner-shell: 2014/12/19 16:16:10 Plugin maximum port: 25000
2014/12/19 16:16:10 packer-provisioner-shell: 2014/12/19 16:16:10 Plugin address: unix /tmp/packer-plugin884305202
2014/12/19 16:16:10 packer-provisioner-shell: 2014/12/19 16:16:10 Waiting for connection...
2014/12/19 16:16:10 packer-provisioner-shell: 2014/12/19 16:16:10 Serving a plugin connection...
2014/12/19 16:16:10 ui: ESC[1;32mopenstack output will be in this color.ESC[0m
2014/12/19 16:16:10 ui: 
2014/12/19 16:16:10 Build debug mode: false
2014/12/19 16:16:10 Force build: false
2014/12/19 16:16:10 Preparing build: openstack
2014/12/19 16:16:10 packer-builder-openstack: 2014/12/19 16:16:10 <Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered> <Filtered>{<Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>B<Filtered>u<Filtered>i<Filtered>l<Filtered>d<Filtered>N<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>o<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>B<Filtered>u<Filtered>i<Filtered>l<Filtered>d<Filtered>e<Filtered>r<Filtered>T<Filtered>y<Filtered>p<Filtered>e<Filtered>:<Filtered>o<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>D<Filtered>e<Filtered>b<Filtered>u<Filtered>g<Filtered>:<Filtered>f<Filtered>a<Filtered>l<Filtered>s<Filtered>e<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>F<Filtered>o<Filtered>r<Filtered>c<Filtered>e<Filtered>:<Filtered>f<Filtered>a<Filtered>l<Filtered>s<Filtered>e<Filtered> <Filtered>P<Filtered>a<Filtered>c<Filtered>k<Filtered>e<Filtered>r<Filtered>U<Filtered>s<Filtered>e<Filtered>r<Filtered>V<Filtered>a<Filtered>r<Filtered>s<Filtered>:<Filtered>m<Filtered>a<Filtered>p<Filtered>[<Filtered>]<Filtered>}<Filtered> <Filtered>A<Filtered>c<Filtered>c<Filtered>e<Filtered>s<Filtered>s<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>U<Filtered>s<Filtered>e<Filtered>r<Filtered>n<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered> <Filtered>P<Filtered>a<Filtered>s<Filtered>s<Filtered>w<Filtered>o<Filtered>r<Filtered>d<Filtered>:<Filtered> <Filtered>A<Filtered>p<Filtered>i<Filtered>K<Filtered>e<Filtered>y<Filtered>:<Filtered> <Filtered>P<Filtered>r<Filtered>o<Filtered>j<Filtered>e<Filtered>c<Filtered>t<Filtered>:<Filtered> <Filtered>P<Filtered>r<Filtered>o<Filtered>v<Filtered>i<Filtered>d<Filtered>e<Filtered>r<Filtered>:<Filtered> <Filtered>R<Filtered>a<Filtered>w<Filtered>R<Filtered>e<Filtered>g<Filtered>i<Filtered>o<Filtered>n<Filtered>:<Filtered> <Filtered>P<Filtered>r<Filtered>o<Filtered>x<Filtered>y<Filtered>U<Filtered>r<Filtered>l<Filtered>:<Filtered> <Filtered>T<Filtered>e<Filtered>n<Filtered>a<Filtered>n<Filtered>t<Filtered>I<Filtered>d<Filtered>:<Filtered> <Filtered>I<Filtered>n<Filtered>s<Filtered>e<Filtered>c<Filtered>u<Filtered>r<Filtered>e<Filtered>:<Filtered>f<Filtered>a<Filtered>l<Filtered>s<Filtered>e<Filtered>}<Filtered> <Filtered>I<Filtered>m<Filtered>a<Filtered>g<Filtered>e<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>I<Filtered>m<Filtered>a<Filtered>g<Filtered>e<Filtered>N<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>c<Filtered>e<Filtered>n<Filtered>t<Filtered>o<Filtered>s<Filtered>-<Filtered>u<Filtered>p<Filtered>d<Filtered>a<Filtered>t<Filtered>e<Filtered>d<Filtered>}<Filtered> <Filtered>R<Filtered>u<Filtered>n<Filtered>C<Filtered>o<Filtered>n<Filtered>f<Filtered>i<Filtered>g<Filtered>:<Filtered>{<Filtered>S<Filtered>o<Filtered>u<Filtered>r<Filtered>c<Filtered>e<Filtered>I<Filtered>m<Filtered>a<Filtered>g<Filtered>e<Filtered>:<Filtered>9<Filtered>0<Filtered>d<Filtered>8<Filtered>d<Filtered>3<Filtered>1<Filtered>c<Filtered>-<Filtered>6<Filtered>3<Filtered>8<Filtered>6<Filtered>-<Filtered>4<Filtered>7<Filtered>4<Filtered>0<Filtered>-<Filtered>8<Filtered>a<Filtered>e<Filtered>5<Filtered>-<Filtered>e<Filtered>8<Filtered>a<Filtered>8<Filtered>0<Filtered>b<Filtered>8<Filtered>f<Filtered>c<Filtered>6<Filtered>d<Filtered>d<Filtered> <Filtered>F<Filtered>l<Filtered>a<Filtered>v<Filtered>o<Filtered>r<Filtered>:<Filtered>2<Filtered> <Filtered>R<Filtered>a<Filtered>w<Filtered>S<Filtered>S<Filtered>H<Filtered>T<Filtered>i<Filtered>m<Filtered>e<Filtered>o<Filtered>u<Filtered>t<Filtered>:<Filtered>5<Filtered>m<Filtered> <Filtered>S<Filtered>S<Filtered>H<Filtered>U<Filtered>s<Filtered>e<Filtered>r<Filtered>n<Filtered>a<Filtered>m<Filtered>e<Filtered>:<Filtered>r<Filtered>o<Filtered>o<Filtered>t<Filtered> <Filtered>S<Filtered>S<Filtered>H<Filtered>P<Filtered>o<Filtered>r<Filtered>t<Filtered>:<Filtered>2<Filtered>2<Filtered> <Filtered>O<Filtered>p<Filtered>e<Filtered>n<Filtered>s<Filtered>t<Filtered>a<Filtered>c<Filtered>k<Filtered>P<Filtered>r<Filtered>o<Filtered>v<Filtered>i<Filtered>d<Filtered>e<Filtered>r<Filtered>:<Filtered> <Filtered>U<Filtered>s<Filtered>e<Filtered>F<Filtered>l<Filtered>o<Filtered>a<Filtered>t<Filtered>i<Filtered>n<Filtered>g<Filtered>I<Filtered>p<Filtered>:<Filtered>t<Filtered>r<Filtered>u<Filtered>e<Filtered> <Filtered>F<Filtered>l<Filtered>o<Filtered>a<Filtered>t<Filtered>i<Filtered>n<Filtered>g<Filtered>I<Filtered>p<Filtered>P<Filtered>o<Filtered>o<Filtered>l<Filtered>:<Filtered>p<Filtered>u<Filtered>b<Filtered>l<Filtered>i<Filtered>c<Filtered> <Filtered>F<Filtered>l<Filtered>o<Filtered>a<Filtered>t<Filtered>i<Filtered>n<Filtered>g<Filtered>I<Filtered>p<Filtered>:<Filtered>1<Filtered>9<Filtered>2<Filtered>.<Filtered>1<Filtered>6<Filtered>8<Filtered>.<Filtered>1<Filtered>0<Filtered>0<Filtered>.<Filtered>2<Filtered>1<Filtered>1<Filtered> <Filtered>S<Filtered>e<Filtered>c<Filtered>u<Filtered>r<Filtered>i<Filtered>t<Filtered>y<Filtered>G<Filtered>r<Filtered>o<Filtered>u<Filtered>p<Filtered>s<Filtered>:<Filtered>[<Filtered>]<Filtered> <Filtered>N<Filtered>e<Filtered>t<Filtered>w<Filtered>o<Filtered>r<Filtered>k<Filtered>s<Filtered>:<Filtered>[<Filtered>4<Filtered>a<Filtered>e<Filtered>f<Filtered>0<Filtered>f<Filtered>3<Filtered>5<Filtered>-<Filtered>8<Filtered>7<Filtered>b<Filtered>5<Filtered>-<Filtered>4<Filtered>d<Filtered>8<Filtered>7<Filtered>-<Filtered>9<Filtered>0<Filtered>0<Filtered>0<Filtered>-<Filtered>d<Filtered>3<Filtered>c<Filtered>a<Filtered>6<Filtered>f<Filtered>0<Filtered>7<Filtered>6<Filtered>9<Filtered>d<Filtered>7<Filtered>]<Filtered> <Filtered>s<Filtered>s<Filtered>h<Filtered>T<Filtered>i<Filtered>m<Filtered>e<Filtered>o<Filtered>u<Filtered>t<Filtered>:<Filtered>3<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>0<Filtered>}<Filtered> <Filtered>t<Filtered>p<Filtered>l<Filtered>:<Filtered>0<Filtered>x<Filtered>c<Filtered>2<Filtered>0<Filtered>8<Filtered>0<Filtered>e<Filtered>f<Filtered>0<Filtered>c<Filtered>0<Filtered>}<Filtered>
2014/12/19 16:16:10 Waiting on builds to complete...
2014/12/19 16:16:10 Starting build run: openstack
2014/12/19 16:16:10 Running builder: openstack
2014/12/19 16:16:11 ui: ESC[1;32m==> openstack: Creating temporary keypair for this instance...ESC[0m
2014/12/19 16:16:11 packer-builder-openstack: 2014/12/19 16:16:11 temporary keypair name: packer 5493d0bb-2321-7a4f-594e-42dd19891563
2014/12/19 16:16:14 packer-builder-openstack: 2014/12/19 16:16:14 server id: b40f2981-57f9-4153-9380-887c6fe45886
2014/12/19 16:16:14 ui: ESC[1;32m==> openstack: Waiting for server (b40f2981-57f9-4153-9380-887c6fe45886) to become ready...ESC[0m
2014/12/19 16:16:14 packer-builder-openstack: 2014/12/19 16:16:14 Waiting for state to become: ACTIVE
2014/12/19 16:16:15 packer-builder-openstack: 2014/12/19 16:16:15 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/12/19 16:16:17 packer-builder-openstack: 2014/12/19 16:16:17 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/12/19 16:16:20 packer-builder-openstack: 2014/12/19 16:16:20 Waiting for state to become: ACTIVE currently BUILD (0%)
2014/12/19 16:16:23 ui: ESC[1;32m==> openstack: Added floating IP 192.168.100.211 to instance...ESC[0m
2014/12/19 16:16:23 packer-builder-openstack: 2014/12/19 16:16:23 Waiting for SSH, up to timeout: 5m0s
2014/12/19 16:16:23 ui: ESC[1;32m==> openstack: Waiting for SSH to become available...ESC[0m
2014/12/19 16:16:27 packer-builder-openstack: 2014/12/19 16:16:27 TCP connection to SSH ip/port failed: dial tcp 192.168.100.211:22: no route to host
2014/12/19 16:16:36 packer-builder-openstack: 2014/12/19 16:16:36 TCP connection to SSH ip/port failed: dial tcp 192.168.100.211:22: no route to host
2014/12/19 16:16:42 packer-builder-openstack: 2014/12/19 16:16:42 TCP connection to SSH ip/port failed: dial tcp 192.168.100.211:22: connection refused
2014/12/19 16:16:47 packer-builder-openstack: 2014/12/19 16:16:47 TCP connection to SSH ip/port failed: dial tcp 192.168.100.211:22: connection refused
2014/12/19 16:16:53 packer-builder-openstack: 2014/12/19 16:16:53 Attempting SSH connection...
2014/12/19 16:16:53 packer-builder-openstack: 2014/12/19 16:16:53 reconnecting to TCP connection for SSH
2014/12/19 16:16:53 packer-builder-openstack: 2014/12/19 16:16:53 handshaking with SSH
2014/12/19 16:16:56 ui: ESC[1;32m==> openstack: Connected to SSH!ESC[0m
2014/12/19 16:16:56 packer-builder-openstack: 2014/12/19 16:16:56 Running the provision hook
2014/12/19 16:16:56 ui: ESC[1;32m==> openstack: Provisioning with shell script: /tmp/packer-shell708381929ESC[0m
2014/12/19 16:16:56 packer-provisioner-shell: 2014/12/19 16:16:56 Opening /tmp/packer-shell708381929 for reading
2014/12/19 16:16:56 packer-provisioner-shell: 2014/12/19 16:16:56 [INFO] 88 bytes written for 'uploadData'
2014/12/19 16:16:56 [INFO] 88 bytes written for 'uploadData'
2014/12/19 16:16:56 packer-builder-openstack: 2014/12/19 16:16:56 opening new ssh session
2014/12/19 16:16:57 packer-builder-openstack: 2014/12/19 16:16:57 Starting remote scp process:  scp -vt /tmp
2014/12/19 16:16:58 packer-builder-openstack: 2014/12/19 16:16:58 Started SCP session, beginning transfers...
2014/12/19 16:16:58 packer-builder-openstack: 2014/12/19 16:16:58 Copying input data into temporary file so we can read the length
2014/12/19 16:16:58 packer-builder-openstack: 2014/12/19 16:16:58 [DEBUG] Uploading script.sh: perms=C0644 size=88
2014/12/19 16:16:58 packer-builder-openstack: 2014/12/19 16:16:58 SCP session complete, closing stdin pipe.
2014/12/19 16:16:58 packer-builder-openstack: 2014/12/19 16:16:58 Waiting for SSH session to complete.
2014/12/19 16:16:58 packer-builder-openstack: 2014/12/19 16:16:58 scp stderr (length 25): Sink: C0644 88 script.sh
2014/12/19 16:16:58 packer-builder-openstack: 2014/12/19 16:16:58 opening new ssh session
2014/12/19 16:16:59 packer-builder-openstack: 2014/12/19 16:16:59 starting remote command: chmod 0777 /tmp/script.sh
2014/12/19 16:16:59 [INFO] RPC client: Communicator ended with: 0
2014/12/19 16:16:59 [INFO] RPC endpoint: Communicator ended with: 0
2014/12/19 16:16:59 packer-provisioner-shell: 2014/12/19 16:16:59 [INFO] RPC client: Communicator ended with: 0
2014/12/19 16:16:59 packer-builder-openstack: 2014/12/19 16:16:59 remote command exited with '0': chmod 0777 /tmp/script.sh
2014/12/19 16:16:59 packer-builder-openstack: 2014/12/19 16:16:59 [INFO] RPC endpoint: Communicator ended with: 0
2014/12/19 16:16:59 packer-builder-openstack: 2014/12/19 16:16:59 opening new ssh session
2014/12/19 16:17:00 packer-builder-openstack: 2014/12/19 16:17:00 starting remote command: chmod +x /tmp/script.sh; PACKER_BUILD_NAME='openstack' PACKER_BUILDER_TYPE='openstack' /tmp/script.sh
2014/12/19 16:17:31 ui: ESC[0;32m    openstack: Loaded plugins: fastestmirror, securityESC[0m
2014/12/19 16:17:31 ui: ESC[0;32m    openstack: Determining fastest mirrorsESC[0m
2014/12/19 16:17:34 ui: ESC[0;32m    openstack: * base: www.ftp.ne.jpESC[0m
2014/12/19 16:17:34 ui: ESC[0;32m    openstack: * extras: www.ftp.ne.jpESC[0m
2014/12/19 16:17:34 ui: ESC[0;32m    openstack: * updates: www.ftp.ne.jpESC[0m
2014/12/19 16:17:34 ui: ESC[0;32m    openstack: base             | 3.7 kB     00:00ESC[0m
2014/12/19 16:17:35 ui: ESC[0;32m    openstack: base/primary_db  | 4.6 MB     00:00ESC[0m
2014/12/19 16:17:36 ui: ESC[0;32m    openstack: extras           | 3.4 kB     00:00ESC[0m
2014/12/19 16:17:36 ui: ESC[0;32m    openstack: extras/primary_d |  30 kB     00:00ESC[0m
2014/12/19 16:17:36 ui: ESC[0;32m    openstack: updates          | 3.4 kB     00:00ESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: updates/primary_ | 1.5 MB     00:00ESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: Setting up Install ProcessESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: Resolving DependenciesESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: --> Running transaction checkESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: ---> Package httpd.x86_64 0:2.2.15-39.el6.centos will be installedESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: --> Processing Dependency: httpd-tools = 2.2.15-39.el6.centos for package: httpd-2.2.15-39.el6.centos.x86_64ESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: --> Processing Dependency: apr-util-ldap for package: httpd-2.2.15-39.el6.centos.x86_64ESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: --> Processing Dependency: /etc/mime.types for package: httpd-2.2.15-39.el6.centos.x86_64ESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: --> Processing Dependency: libaprutil-1.so.0()(64bit) for package: httpd-2.2.15-39.el6.centos.x86_64ESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: --> Processing Dependency: libapr-1.so.0()(64bit) for package: httpd-2.2.15-39.el6.centos.x86_64ESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: --> Running transaction checkESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: ---> Package apr.x86_64 0:1.3.9-5.el6_2 will be installedESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: ---> Package apr-util.x86_64 0:1.3.9-3.el6_0.1 will be installedESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: ---> Package apr-util-ldap.x86_64 0:1.3.9-3.el6_0.1 will be installedESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: ---> Package httpd-tools.x86_64 0:2.2.15-39.el6.centos will be installedESC[0m
2014/12/19 16:17:37 ui: ESC[0;32m    openstack: ---> Package mailcap.noarch 0:2.1.31-2.el6 will be installedESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: --> Finished Dependency ResolutionESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Dependencies ResolvedESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: ========================================ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Package       Arch   VersionESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: RepositoryESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: SizeESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: ========================================ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Installing:ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: httpd         x86_64 2.2.15-39.el6.centosESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: base 825 kESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Installing for dependencies:ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: apr           x86_64 1.3.9-5.el6_2ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: base 123 kESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: apr-util      x86_64 1.3.9-3.el6_0.1ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: base  87 kESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: apr-util-ldap x86_64 1.3.9-3.el6_0.1ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: base  15 kESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: httpd-tools   x86_64 2.2.15-39.el6.centosESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: base  75 kESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: mailcap       noarch 2.1.31-2.el6ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: base  27 kESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Transaction SummaryESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: ========================================ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Install       6 Package(s)ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Total download size: 1.1 MESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Installed size: 3.6 MESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: Downloading Packages:ESC[0m
2014/12/19 16:17:38 ui: ESC[0;32m    openstack: (1/6): apr-1.3.9 | 123 kB     00:00ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: (2/6): apr-util- |  87 kB     00:00ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: (3/6): apr-util- |  15 kB     00:00ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: (4/6): httpd-2.2 | 825 kB     00:00ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: (5/6): httpd-too |  75 kB     00:00ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: (6/6): mailcap-2 |  27 kB     00:00ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: ----------------------------------------ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: Total            | 1.1 MB     00:00ESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: Running rpm_check_debugESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: Running Transaction TestESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: Transaction Test SucceededESC[0m
2014/12/19 16:17:39 ui: ESC[0;32m    openstack: Running TransactionESC[0m
2014/12/19 16:17:40 ui: ESC[0;32m    openstack:   Installing : apr-1.3.9-5.el6_2.   1/6ESC[0m
2014/12/19 16:17:41 ui: ESC[0;32m    openstack:   Installing : apr-util-1.3.9-3.e   2/6ESC[0m
2014/12/19 16:17:42 ui: ESC[0;32m    openstack:   Installing : httpd-tools-2.2.15   3/6ESC[0m
2014/12/19 16:17:43 ui: ESC[0;32m    openstack:   Installing : apr-util-ldap-1.3.   4/6ESC[0m
2014/12/19 16:17:43 ui: ESC[0;32m    openstack:   Installing : mailcap-2.1.31-2.e   5/6ESC[0m
2014/12/19 16:17:45 ui: ESC[0;32m    openstack:   Installing : httpd-2.2.15-39.el   6/6ESC[0m
2014/12/19 16:17:46 ui: ESC[0;32m    openstack: Verifying  : httpd-2.2.15-39.el   1/6ESC[0m
2014/12/19 16:17:46 ui: ESC[0;32m    openstack: Verifying  : httpd-tools-2.2.15   2/6ESC[0m
2014/12/19 16:17:46 ui: ESC[0;32m    openstack: Verifying  : apr-util-ldap-1.3.   3/6ESC[0m
2014/12/19 16:17:46 ui: ESC[0;32m    openstack: Verifying  : apr-1.3.9-5.el6_2.   4/6ESC[0m
2014/12/19 16:17:46 ui: ESC[0;32m    openstack: Verifying  : mailcap-2.1.31-2.e   5/6ESC[0m
2014/12/19 16:17:47 [INFO] RPC client: Communicator ended with: 0
2014/12/19 16:17:47 [INFO] 0 bytes written for 'stderr'
2014/12/19 16:17:47 [INFO] RPC endpoint: Communicator ended with: 0
2014/12/19 16:17:47 [INFO] 4832 bytes written for 'stdout'
2014/12/19 16:17:47 packer-builder-openstack: 2014/12/19 16:17:47 remote command exited with '0': chmod +x /tmp/script.sh; PACKER_BUILD_NAME='openstack' PACKER_BUILDER_TYPE='openstack' /tmp/script.sh
2014/12/19 16:17:47 packer-builder-openstack: 2014/12/19 16:17:47 [INFO] RPC endpoint: Communicator ended with: 0
2014/12/19 16:17:47 packer-provisioner-shell: 2014/12/19 16:17:47 [INFO] RPC client: Communicator ended with: 0
2014/12/19 16:17:47 packer-provisioner-shell: 2014/12/19 16:17:47 [INFO] 0 bytes written for 'stderr'
2014/12/19 16:17:47 packer-provisioner-shell: 2014/12/19 16:17:47 [INFO] 4832 bytes written for 'stdout'
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: Verifying  : apr-util-1.3.9-3.e   6/6ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: Installed:ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: httpd.x86_64 0:2.2.15-39.el6.centosESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: Dependency Installed:ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: apr.x86_64 0:1.3.9-5.el6_2ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: apr-util.x86_64 0:1.3.9-3.el6_0.1ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: apr-util-ldap.x86_64 0:1.3.9-3.el6_0.1ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: httpd-tools.x86_64 0:2.2.15-39.el6.centosESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: mailcap.noarch 0:2.1.31-2.el6ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack:ESC[0m
2014/12/19 16:17:47 ui: ESC[0;32m    openstack: Complete!ESC[0m
2014/12/19 16:17:47 ui: ESC[1;32m==> openstack: Creating the image: centos-updatedESC[0m
2014/12/19 16:17:48 ui: ESC[1;32m==> openstack: Image: cfe8f85c-909f-4298-9eee-0fdcd8e0e217ESC[0m
2014/12/19 16:17:48 ui: ESC[1;32m==> openstack: Waiting for image to become ready...ESC[0m
2014/12/19 16:17:49 packer-builder-openstack: 2014/12/19 16:17:49 Waiting for image creation status: SAVING (25%)
2014/12/19 16:17:52 packer-builder-openstack: 2014/12/19 16:17:52 Waiting for image creation status: SAVING (25%)
2014/12/19 16:17:55 packer-builder-openstack: 2014/12/19 16:17:55 Waiting for image creation status: SAVING (25%)
2014/12/19 16:17:58 packer-builder-openstack: 2014/12/19 16:17:58 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:00 packer-builder-openstack: 2014/12/19 16:18:00 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:03 packer-builder-openstack: 2014/12/19 16:18:03 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:05 packer-builder-openstack: 2014/12/19 16:18:05 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:07 packer-builder-openstack: 2014/12/19 16:18:07 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:10 packer-builder-openstack: 2014/12/19 16:18:10 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:12 packer-builder-openstack: 2014/12/19 16:18:12 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:15 packer-builder-openstack: 2014/12/19 16:18:15 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:18 packer-builder-openstack: 2014/12/19 16:18:18 Waiting for image creation status: SAVING (25%)
2014/12/19 16:18:21 ui: ESC[1;32m==> openstack: Terminating the source server...ESC[0m
2014/12/19 16:18:22 packer-builder-openstack: 2014/12/19 16:18:22 Waiting for state to become: DELETED
2014/12/19 16:18:22 packer-builder-openstack: 2014/12/19 16:18:22 Waiting for state to become: DELETED currently ACTIVE (0%)
2014/12/19 16:18:25 packer-builder-openstack: 2014/12/19 16:18:25 404 on ServerStateRefresh, returning DELETED
2014/12/19 16:18:25 ui: ESC[1;32m==> openstack: Deleting temporary keypair...ESC[0m
2014/12/19 16:18:25 packer-builder-openstack: panic: runtime error: invalid memory address or nil pointer dereference
2014/12/19 16:18:25 packer-builder-openstack: [signal 0xb code=0x1 addr=0x0 pc=0x433305]
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 33 [running]:
2014/12/19 16:18:25 packer-builder-openstack: runtime.panic(0x843540, 0xb0c4f3)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/panic.c:279 +0xf5
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.WaitForImage(0x7eff3f9e9c68, 0xc2080c32f0, 0xc2080e489c, 0x24, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/step_create_image.go:62 +0x215
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.(*stepCreateImage).Run(0xb11d40, 0x7eff3f9e9f00, 0xc2080c3320, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/step_create_image.go:40 +0x73d
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/multistep.(*BasicRunner).Run(0xc208039600, 0x7eff3f9e9f00, 0xc2080c3320)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/multistep/basic_runner.go:70 +0x3a1
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.(*Builder).Run(0xc20802a9c0, 0x7eff3f9e9660, 0xc2080ef340, 0x7eff3f9e96a8, 0xc2080db0e0, 0x7eff3f9e96d8, 0xc20803a058, 0x0, 0x0, 0x0, ...)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/builder.go:121 +0xb92
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc2080c0840, 0x1, 0xc208000aac, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x34e
2014/12/19 16:18:25 packer-builder-openstack: reflect.Value.call(0x7dca40, 0x83f7b8, 0x0, 0x130, 0x89df50, 0x4, 0xc208004060, 0x3, 0x3, 0x0, ...)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/reflect/value.go:563 +0x1210
2014/12/19 16:18:25 packer-builder-openstack: reflect.Value.Call(0x7dca40, 0x83f7b8, 0x0, 0x130, 0xc208004060, 0x3, 0x3, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/reflect/value.go:411 +0xd7
2014/12/19 16:18:25 packer-builder-openstack: net/rpc.(*service).call(0xc2080173b0, 0xc208039c40, 0xc2080da018, 0xc208044480, 0xc2080c0ae0, 0x75cb00, 0xc208000aa8, 0x0, 0xa6, 0x742000, ...)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:382 +0x1c7
2014/12/19 16:18:25 packer-builder-openstack: created by net/rpc.(*Server).ServeCodec
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:453 +0x427
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 16 [select, 2 minutes]:
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/yamux.(*Stream).Read(0xc208042a00, 0xc2080e9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/stream.go:123 +0x382
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).fill(0xc2080ea000)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).ReadByte(0xc2080ea000, 0x82, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:199 +0x7e
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*ioDecReader).readn1(0xc2080d60c0, 0x160)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:90 +0x44
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).initReadNext(0xc2080ee040)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:540 +0x48
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).decode(0xc2080ea060, 0x73c9c0, 0xc2080ee060)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:635 +0x58
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).Decode(0xc2080ea060, 0x73c9c0, 0xc2080ee060, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:630 +0x7c
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*rpcCodec).read(0xc2080e20c0, 0x73c9c0, 0xc2080ee060, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:88 +0xd6
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*goRpcCodec).ReadRequestHeader(0xc2080e20c0, 0xc2080ee060, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:127 +0x5e
2014/12/19 16:18:25 packer-builder-openstack: net/rpc.(*Server).readRequestHeader(0xc208039c40, 0x7eff3f9e9140, 0xc2080e20c0, 0x0, 0x0, 0xc2080ee060, 0x989000, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:552 +0x9b
2014/12/19 16:18:25 packer-builder-openstack: net/rpc.(*Server).readRequest(0xc208039c40, 0x7eff3f9e9140, 0xc2080e20c0, 0xc208044480, 0xc2080c0ae0, 0x75cb00, 0x0, 0x0, 0x0, 0x0, ...)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:519 +0xbe
2014/12/19 16:18:25 packer-builder-openstack: net/rpc.(*Server).ServeCodec(0xc208039c40, 0x7eff3f9e9140, 0xc2080e20c0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:438 +0x69
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*Server).Serve(0xc2080c0800)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/server.go:149 +0x23a
2014/12/19 16:18:25 packer-builder-openstack: main.main()
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/plugin/builder-openstack/main.go:14 +0xc5
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 19 [finalizer wait, 2 minutes]:
2014/12/19 16:18:25 packer-builder-openstack: runtime.park(0x412ce0, 0xb110b0, 0xb0f269)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1369 +0x89
2014/12/19 16:18:25 packer-builder-openstack: runtime.parkunlock(0xb110b0, 0xb0f269)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1385 +0x3b
2014/12/19 16:18:25 packer-builder-openstack: runfinq()
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/mgc0.c:2644 +0xcf
2014/12/19 16:18:25 packer-builder-openstack: runtime.goexit()
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1445
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 20 [syscall, 2 minutes]:
2014/12/19 16:18:25 packer-builder-openstack: os/signal.loop()
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
2014/12/19 16:18:25 packer-builder-openstack: created by os/signal.init·1
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:27 +0x32
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 22 [chan receive, 2 minutes]:
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/packer/packer/plugin.func·017()
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:92 +0x62
2014/12/19 16:18:25 packer-builder-openstack: created by github.com/mitchellh/packer/packer/plugin.Server
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:96 +0xa8f
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 23 [runnable]:
2014/12/19 16:18:25 packer-builder-openstack: net.runtime_pollWait(0x7eff3f9e89a0, 0x72, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/netpoll.goc:146 +0x66
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).Wait(0xc2080b7410, 0x72, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).WaitRead(0xc2080b7410, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
2014/12/19 16:18:25 packer-builder-openstack: net.(*netFD).Read(0xc2080b73b0, 0xc2080c7000, 0x1000, 0x1000, 0x0, 0x7eff3f9e72b8, 0xb)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_unix.go:242 +0x34c
2014/12/19 16:18:25 packer-builder-openstack: net.(*conn).Read(0xc20803a090, 0xc2080c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/net.go:122 +0xe7
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).fill(0xc208004480)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).Read(0xc208004480, 0xc2080ba800, 0xc, 0xc, 0xc, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:175 +0x230
2014/12/19 16:18:25 packer-builder-openstack: io.ReadAtLeast(0x7eff3f9e8c20, 0xc208004480, 0xc2080ba800, 0xc, 0xc, 0xc, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:289 +0xf7
2014/12/19 16:18:25 packer-builder-openstack: io.ReadFull(0x7eff3f9e8c20, 0xc208004480, 0xc2080ba800, 0xc, 0xc, 0xc, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:307 +0x71
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).recv(0xc208048640)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:332 +0xc9
2014/12/19 16:18:25 packer-builder-openstack: created by github.com/hashicorp/yamux.newSession
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:93 +0x247
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 24 [select]:
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).send(0xc208048640)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:290 +0x496
2014/12/19 16:18:25 packer-builder-openstack: created by github.com/hashicorp/yamux.newSession
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:94 +0x25f
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 25 [select]:
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).keepalive(0xc208048640)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:246 +0xc7
2014/12/19 16:18:25 packer-builder-openstack: created by github.com/hashicorp/yamux.newSession
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:96 +0x289
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 26 [select]:
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).AcceptStream(0xc208048640, 0xc200000001, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:154 +0x11f
2014/12/19 16:18:25 packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*muxBroker).Run(0xc2080c07e0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/mux_broker.go:126 +0x36
2014/12/19 16:18:25 packer-builder-openstack: created by github.com/mitchellh/packer/packer/rpc.NewServer
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/server.go:43 +0x77
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 59 [runnable]:
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/yamux.(*Stream).Read(0xc2080f0140, 0xc2080ff000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/yamux/stream.go:123 +0x382
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).fill(0xc2080ea960)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).ReadByte(0xc2080ea960, 0x66e484, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:199 +0x7e
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*ioDecReader).readn1(0xc2080d7350, 0xc20814b6e0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:90 +0x44
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).initReadNext(0xc2080ef300)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:540 +0x48
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).decode(0xc2080ea9c0, 0x73ca20, 0xc2080d7920)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:635 +0x58
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).Decode(0xc2080ea9c0, 0x73ca20, 0xc2080d7920, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:630 +0x7c
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*rpcCodec).read(0xc2080e2b00, 0x73ca20, 0xc2080d7920, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:88 +0xd6
2014/12/19 16:18:25 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*goRpcCodec).ReadResponseHeader(0xc2080e2b00, 0xc2080d7920, 0x0, 0x0)
2014/12/19 16:18:25 ui error: ESC[1;31mBuild 'openstack' errored: unexpected EOFESC[0m
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:123 +0x5e
2014/12/19 16:18:25 packer-builder-openstack: net/rpc.(*Client).input(0xc2080eaa20)
2014/12/19 16:18:25 Builds completed. Waiting on interrupt barrier...
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/client.go:109 +0xda
2014/12/19 16:18:25 machine readable: error-count []string{"1"}
2014/12/19 16:18:25 ui error: 
==> Some builds didn't complete successfully and had errors:
2014/12/19 16:18:25 packer-builder-openstack: created by net/rpc.NewClientWithCodec
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/client.go:201 +0x8b
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 34 [IO wait, 2 minutes]:
2014/12/19 16:18:25 packer-builder-openstack: net.runtime_pollWait(0x7eff3f9e8a50, 0x72, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/netpoll.goc:146 +0x66
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).Wait(0xc208028ed0, 0x72, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).WaitRead(0xc208028ed0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
2014/12/19 16:18:25 packer-builder-openstack: net.(*netFD).Read(0xc208028e70, 0xc208102000, 0x1000, 0x1000, 0x0, 0x7eff3f9e72b8, 0xb)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_unix.go:242 +0x34c2014/12/19 16:18:25 packer-builder-openstack: net.(*conn).Read(0xc208100000, 0xc208102000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/net.go:122 +0xe7
2014/12/19 16:18:25 packer-builder-openstack: net/http.noteEOFReader.Read(0x7eff3f9e9910, 0xc208100000, 0xc20804e058, 0xc208102000, 0x1000, 0x1000, 0xb23e20, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:1203 +0x72
2014/12/19 16:18:25 packer-builder-openstack: net/http.(*noteEOFReader).Read(0xc208040c40, 0xc208102000, 0x1000, 0x1000, 0xc2080e05f0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   <autogenerated>:124 +0xca
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).fill(0xc2080046c0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).Peek(0xc2080046c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:132 +0x101
2014/12/19 16:18:25 machine readable: openstack,error []string{"unexpected EOF"}
2014/12/19 16:18:25 ui error: --> openstack: unexpected EOF
2014/12/19 16:18:25 ui: 
==> Builds finished but no artifacts were created.
2014/12/19 16:18:25 waiting for all plugin processes to complete...
2014/12/19 16:18:25 packer-builder-openstack: net/http.(*persistConn).readLoop(0xc20804e000)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:782 +0x95
2014/12/19 16:18:25 packer-builder-openstack: created by net/http.(*Transport).dialConn
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:600 +0x93f
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 35 [select, 2 minutes]:
2014/12/19 16:18:25 packer-builder-openstack: net/http.(*persistConn).writeLoop(0xc20804e000)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:885 +0x38f
2014/12/19 16:18:25 packer-builder-openstack: created by net/http.(*Transport).dialConn
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:601 +0x957
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 38 [IO wait]:
2014/12/19 16:18:25 packer-builder-openstack: net.runtime_pollWait(0x7eff3f9e88f0, 0x72, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/netpoll.goc:146 +0x66
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).Wait(0xc2080b6f40, 0x72, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).WaitRead(0xc2080b6f40, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
2014/12/19 16:18:25 packer-builder-openstack: net.(*netFD).Read(0xc2080b6ee0, 0xc208132000, 0x1000, 0x1000, 0x0, 0x7eff3f9e72b8, 0xb)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_unix.go:242 +0x34c
2014/12/19 16:18:25 packer-builder-openstack: net.(*conn).Read(0xc2081000b0, 0xc208132000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/net.go:122 +0xe7
2014/12/19 16:18:25 packer-builder-openstack: net/http.noteEOFReader.Read(0x7eff3f9e9910, 0xc2081000b0, 0xc20804e3c8, 0xc208132000, 0x1000, 0x1000, 0x403fc0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:1203 +0x72
2014/12/19 16:18:25 packer-builder-openstack: net/http.(*noteEOFReader).Read(0xc2080c0240, 0xc208132000, 0x1000, 0x1000, 0xc2080e05f0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   <autogenerated>:124 +0xca
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).fill(0xc208004de0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).Peek(0xc208004de0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:132 +0x101
2014/12/19 16:18:25 packer-builder-openstack: net/http.(*persistConn).readLoop(0xc20804e370)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:782 +0x95
2014/12/19 16:18:25 packer-builder-openstack: created by net/http.(*Transport).dialConn
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:600 +0x93f
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 39 [select]:
2014/12/19 16:18:25 packer-builder-openstack: net/http.(*persistConn).writeLoop(0xc20804e370)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:885 +0x38f
2014/12/19 16:18:25 /home/vagrant/packer/packer-provisioner-shell: plugin process exited
2014/12/19 16:18:25 packer-builder-openstack: created by net/http.(*Transport).dialConn
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:601 +0x957
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 41 [IO wait]:
2014/12/19 16:18:25 packer-builder-openstack: net.runtime_pollWait(0x7eff3f9e8840, 0x72, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/netpoll.goc:146 +0x66
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).Wait(0xc2080df560, 0x72, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
2014/12/19 16:18:25 packer-builder-openstack: net.(*pollDesc).WaitRead(0xc2080df560, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
2014/12/19 16:18:25 packer-builder-openstack: net.(*netFD).Read(0xc2080df500, 0xc208110000, 0x1000, 0x1000, 0x0, 0x7eff3f9e72b8, 0xb)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_unix.go:242 +0x34c
2014/12/19 16:18:25 packer-builder-openstack: net.(*conn).Read(0xc208100020, 0xc208110000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/net/net.go:122 +0xe7
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).fill(0xc2080b2000)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2014/12/19 16:18:25 packer-builder-openstack: bufio.(*Reader).Read(0xc2080b2000, 0xc2080461a0, 0x5, 0x5, 0x5, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:175 +0x230
2014/12/19 16:18:25 packer-builder-openstack: io.ReadAtLeast(0x7eff3f9e8c20, 0xc2080b2000, 0xc2080461a0, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:289 +0xf7
2014/12/19 16:18:25 packer-builder-openstack: io.ReadFull(0x7eff3f9e8c20, 0xc2080b2000, 0xc2080461a0, 0x5, 0x5, 0x354, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:307 +0x71
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*streamPacketCipher).readPacket(0xc208046180, 0xc200000071, 0x7eff3f9e8c20, 0xc2080b2000, 0x0, 0x0, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/cipher.go:137 +0xd8
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*connectionState).readPacket(0xc2080f2000, 0xc2080b2000, 0x0, 0x0, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/transport.go:110 +0xe7
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*transport).readPacket(0xc2080f2000, 0x0, 0x0, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/transport.go:106 +0x67
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*handshakeTransport).readOnePacket(0xc208146000, 0x0, 0x0, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:153 +0x105
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*handshakeTransport).readLoop(0xc208146000)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:133 +0x27
2014/12/19 16:18:25 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.newClientTransport
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:101 +0x101
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 42 [chan receive]:
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*handshakeTransport).readPacket(0xc208146000, 0x0, 0x0, 0x0, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:124 +0x86
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*mux).onePacket(0xc2080de000, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:224 +0x66
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*mux).loop(0xc2080de000)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:199 +0x49
2014/12/19 16:18:25 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.newMux
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:128 +0xee
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 43 [chan receive]:
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*Client).handleGlobalRequests(0xc208039280, 0xc2080582a0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:133 +0x4d
2014/12/19 16:18:25 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:54 +0xb6
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 44 [chan receive]:
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*Client).handleChannelOpens(0xc208039280, 0xc208108000)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:142 +0x64
2014/12/19 16:18:25 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:55 +0xdb
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 45 [semacquire]:
2014/12/19 16:18:25 packer-builder-openstack: sync.runtime_Syncsemacquire(0xc208039250)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/runtime/sema.goc:257 +0xc0
2014/12/19 16:18:25 packer-builder-openstack: sync.(*Cond).Wait(0xc208039240)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/3rdparty/go/src/pkg/sync/cond.go:62 +0x9d
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*mux).Wait(0xc2080de000, 0x0, 0x0)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:110 +0xb5
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.func·003()
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:57 +0x47
2014/12/19 16:18:25 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2014/12/19 16:18:25 /home/vagrant/packer/packer-builder-openstack: plugin process exited
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:59 +0x108
2014/12/19 16:18:25 packer-builder-openstack: 
2014/12/19 16:18:25 packer-builder-openstack: goroutine 46 [chan receive]:
2014/12/19 16:18:25 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*forwardList).handleChannels(0xc208039290, 0xc208108160)
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/tcpip.go:178 +0x73
2014/12/19 16:18:25 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2014/12/19 16:18:25 packer-builder-openstack:   /Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:60 +0x15b
```

### LINKED ISSUE #1966: Crash imaging openstack server
```
1425650539,,ui,say,==> openstack: Creating the image: academy
1425650541,,ui,say,==> openstack: Image: 2084d859-fc01-4c6a-9578-64292fd9cffb
1425650541,,ui,say,==> openstack: Waiting for image to become ready...
1425650882,,ui,say,==> openstack: Terminating the source server...
1425650888,,ui,say,==> openstack: Deleting temporary keypair...
1425650888,,ui,error,Build 'openstack' errored: unexpected EOF
1425650888,,error-count,1
1425650888,,ui,error,\n==> Some builds didn't complete successfully and had errors:
1425650888,openstack,error,unexpected EOF
1425650888,,ui,error,--> openstack: unexpected EOF
1425650888,,ui,say,\n==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2015/03/06 14:08:08 packer-builder-openstack: [signal 0xb code=0x1 addr=0x0 pc=0x34625]
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 66 [running]:
2015/03/06 14:08:08 packer-builder-openstack: runtime.panic(0x447600, 0x715504)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/panic.c:279 +0xf5
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.WaitForImage(0xa12c40, 0xc2080a1ce0, 0xc2081625cc, 0x24, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/step_create_image.go:62 +0x215
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.(*stepCreateImage).Run(0x719838, 0xa12ed8, 0xc2080a1d10, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/step_create_image.go:40 +0x73d
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/multistep.(*BasicRunner).Run(0xc20803dd00, 0xa12ed8, 0xc2080a1d10)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/multistep/basic_runner.go:70 +0x3a1
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/packer/builder/openstack.(*Builder).Run(0xc20802f040, 0xa12638, 0xc2080fe0e0, 0xa12680, 0xc208000de0, 0xa126b0, 0xc208124000, 0x0, 0x0, 0x0, ...)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/builder/openstack/builder.go:121 +0xb92
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc20809e600, 0x1, 0xc208000d80, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x34e
2015/03/06 14:08:08 packer-builder-openstack: reflect.Value.call(0x3e06a0, 0x443878, 0x0, 0x130, 0x4a2d10, 0x4, 0xc208004600, 0x3, 0x3, 0x0, ...)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/reflect/value.go:563 +0x1210
2015/03/06 14:08:08 packer-builder-openstack: reflect.Value.Call(0x3e06a0, 0x443878, 0x0, 0x130, 0xc208004600, 0x3, 0x3, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/reflect/value.go:411 +0xd7
2015/03/06 14:08:08 packer-builder-openstack: net/rpc.(*service).call(0xc20801b6d0, 0xc20803da80, 0xc2080bc018, 0xc208048360, 0xc2080450a0, 0x3602c0, 0xc208000d6c, 0x0, 0xa6, 0x345160, ...)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:382 +0x1c7
2015/03/06 14:08:08 packer-builder-openstack: created by net/rpc.(*Server).ServeCodec
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:453 +0x427
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 16 [select, 12 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/yamux.(*Stream).Read(0xc2080c2000, 0xc2080ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/stream.go:123 +0x382
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).fill(0xc2080de060)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).ReadByte(0xc2080de060, 0x82, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:199 +0x7e
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*ioDecReader).readn1(0xc2080e80f0, 0x160)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:90 +0x44
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).initReadNext(0xc208044720)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:540 +0x48
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).decode(0xc2080de0c0, 0x33fac0, 0xc208044760)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:635 +0x58
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).Decode(0xc2080de0c0, 0x33fac0, 0xc208044760, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:630 +0x7c
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*rpcCodec).read(0xc2080d2080, 0x33fac0, 0xc208044760, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:88 +0xd6
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*goRpcCodec).ReadRequestHeader(0xc2080d2080, 0xc208044760, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:127 +0x5e
2015/03/06 14:08:08 packer-builder-openstack: net/rpc.(*Server).readRequestHeader(0xc20803da80, 0xa12118, 0xc2080d2080, 0x0, 0x0, 0xc208044760, 0x58ea00, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:552 +0x9b
2015/03/06 14:08:08 packer-builder-openstack: net/rpc.(*Server).readRequest(0xc20803da80, 0xa12118, 0xc2080d2080, 0xc208048360, 0xc2080450a0, 0x3602c0, 0x0, 0x0, 0x0, 0x0, ...)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:519 +0xbe
2015/03/06 14:08:08 packer-builder-openstack: net/rpc.(*Server).ServeCodec(0xc20803da80, 0xa12118, 0xc2080d2080)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/server.go:438 +0x69
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*Server).Serve(0xc20809e5e0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/server.go:149 +0x23a
2015/03/06 14:08:08 packer-builder-openstack: main.main()
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/plugin/builder-openstack/main.go:14 +0xc5
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 19 [finalizer wait, 12 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: runtime.park(0x14370, 0x718b98, 0x7175c9)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1369 +0x89
2015/03/06 14:08:08 packer-builder-openstack: runtime.parkunlock(0x718b98, 0x7175c9)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1385 +0x3b
2015/03/06 14:08:08 packer-builder-openstack: runfinq()
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/mgc0.c:2644 +0xcf
2015/03/06 14:08:08 packer-builder-openstack: runtime.goexit()
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1445
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 20 [syscall, 12 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: os/signal.loop()
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
2015/03/06 14:08:08 packer-builder-openstack: created by os/signal.init·1
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:27 +0x32
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 22 [chan receive, 12 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/packer/packer/plugin.func·017()
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:92 +0x62
2015/03/06 14:08:08 packer-builder-openstack: created by github.com/mitchellh/packer/packer/plugin.Server
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:96 +0xa8f
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 23 [runnable]:
2015/03/06 14:08:08 packer-builder-openstack: syscall.Syscall(0x3, 0x5, 0xc2080aa000, 0x1000, 0xc, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/syscall/asm_darwin_amd64.s:20 +0x5
2015/03/06 14:08:08 packer-builder-openstack: syscall.read(0x5, 0xc2080aa000, 0x1000, 0x1000, 0x72, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/syscall/zsyscall_darwin_amd64.go:952 +0x75
2015/03/06 14:08:08 packer-builder-openstack: syscall.Read(0x5, 0xc2080aa000, 0x1000, 0x1000, 0xffffffffffffff01, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/syscall/syscall_unix.go:136 +0x5c
2015/03/06 14:08:08 packer-builder-openstack: net.(*netFD).Read(0xc2080933b0, 0xc2080aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_unix.go:238 +0x273
2015/03/06 14:08:08 packer-builder-openstack: net.(*conn).Read(0xc20803e090, 0xc2080aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/net.go:122 +0xe7
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).fill(0xc208004480)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).Read(0xc208004480, 0xc2080bc004, 0xc, 0xc, 0xc, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:175 +0x230
2015/03/06 14:08:08 packer-builder-openstack: io.ReadAtLeast(0xa11bf8, 0xc208004480, 0xc2080bc004, 0xc, 0xc, 0xc, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:289 +0xf7
2015/03/06 14:08:08 packer-builder-openstack: io.ReadFull(0xa11bf8, 0xc208004480, 0xc2080bc004, 0xc, 0xc, 0xc, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:307 +0x71
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).recv(0xc20804c640)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:332 +0xc9
2015/03/06 14:08:08 packer-builder-openstack: created by github.com/hashicorp/yamux.newSession
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:93 +0x247
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 24 [select]:
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).send(0xc20804c640)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:290 +0x496
2015/03/06 14:08:08 packer-builder-openstack: created by github.com/hashicorp/yamux.newSession
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:94 +0x25f
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 25 [select]:
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).keepalive(0xc20804c640)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:246 +0xc7
2015/03/06 14:08:08 packer-builder-openstack: created by github.com/hashicorp/yamux.newSession
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:96 +0x289
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 26 [select, 10 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/yamux.(*Session).AcceptStream(0xc20804c640, 0xc200000001, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:154 +0x11f
2015/03/06 14:08:08 packer-builder-openstack: github.com/mitchellh/packer/packer/rpc.(*muxBroker).Run(0xc20809e5c0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/mux_broker.go:126 +0x36
2015/03/06 14:08:08 packer-builder-openstack: created by github.com/mitchellh/packer/packer/rpc.NewServer
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/server.go:43 +0x77
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 67 [runnable]:
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/yamux.(*Stream).Read(0xc2080c23c0, 0xc208121000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/stream.go:123 +0x382
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).fill(0xc208004780)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).ReadByte(0xc208004780, 0x2711f4, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:199 +0x7e
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*ioDecReader).readn1(0xc2080a03f0, 0xc2081506c0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:90 +0x44
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).initReadNext(0xc2080fe0a0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:540 +0x48
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).decode(0xc2080047e0, 0x33fb20, 0xc2080be8d0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:635 +0x58
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*Decoder).Decode(0xc2080047e0, 0x33fb20, 0xc2080be8d0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:630 +0x7c
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*rpcCodec).read(0xc20803d580, 0x33fb20, 0xc2080be8d0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:88 +0xd6
2015/03/06 14:08:08 packer-builder-openstack: github.com/hashicorp/go-msgpack/codec.(*goRpcCodec).ReadResponseHeader(0xc20803d580, 0xc2080be8d0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:123 +0x5e
2015/03/06 14:08:08 packer-builder-openstack: net/rpc.(*Client).input(0xc208004840)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/client.go:109 +0xda
2015/03/06 14:08:08 packer-builder-openstack: created by net/rpc.NewClientWithCodec
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/rpc/client.go:201 +0x8b
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 74 [chan receive, 10 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*Client).handleGlobalRequests(0xc2080d2240, 0xc208100460)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:133 +0x4d
2015/03/06 14:08:08 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:54 +0xb6
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 54 [IO wait, 5 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: net.runtime_pollWait(0xa118c8, 0x72, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/netpoll.goc:146 +0x66
2015/03/06 14:08:08 packer-builder-openstack: net.(*pollDesc).Wait(0xc2081ca6f0, 0x72, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
2015/03/06 14:08:08 packer-builder-openstack: net.(*pollDesc).WaitRead(0xc2081ca6f0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
2015/03/06 14:08:08 packer-builder-openstack: net.(*netFD).Read(0xc2081ca690, 0xc208155000, 0x1000, 0x1000, 0x0, 0xa10290, 0x23)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_unix.go:242 +0x34c
2015/03/06 14:08:08 packer-builder-openstack: net.(*conn).Read(0xc20803e0c0, 0xc208155000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/net.go:122 +0xe7
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).fill(0xc2080de180)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).Read(0xc2080de180, 0xc2081029a0, 0x5, 0x5, 0x5, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:175 +0x230
2015/03/06 14:08:08 packer-builder-openstack: io.ReadAtLeast(0xa11bf8, 0xc2080de180, 0xc2081029a0, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:289 +0xf7
2015/03/06 14:08:08 packer-builder-openstack: io.ReadFull(0xa11bf8, 0xc2080de180, 0xc2081029a0, 0x5, 0x5, 0x1024, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/io/io.go:307 +0x71
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*streamPacketCipher).readPacket(0xc208102980, 0xc2000006a2, 0xa11bf8, 0xc2080de180, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/cipher.go:137 +0xd8
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*connectionState).readPacket(0xc2081ba240, 0xc2080de180, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/transport.go:110 +0xe7
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*transport).readPacket(0xc2081ba240, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/transport.go:106 +0x67
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*handshakeTransport).readOnePacket(0xc20812c000, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:153 +0x105
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*handshakeTransport).readLoop(0xc20812c000)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:133 +0x27
2015/03/06 14:08:08 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.newClientTransport
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:101 +0x101
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 73 [chan receive, 5 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*handshakeTransport).readPacket(0xc20812c000, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/handshake.go:124 +0x86
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*mux).onePacket(0xc2080c4460, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:224 +0x66
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*mux).loop(0xc2080c4460)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:199 +0x49
2015/03/06 14:08:08 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.newMux
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:128 +0xee
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 75 [chan receive, 10 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*Client).handleChannelOpens(0xc2080d2240, 0xc20808c2c0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:142 +0x64
2015/03/06 14:08:08 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:55 +0xdb
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 76 [semacquire, 10 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: sync.runtime_Syncsemacquire(0xc2080d2210)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/sema.goc:257 +0xc0
2015/03/06 14:08:08 packer-builder-openstack: sync.(*Cond).Wait(0xc2080d2200)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/sync/cond.go:62 +0x9d
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*mux).Wait(0xc2080c4460, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/mux.go:110 +0xb5
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.func·003()
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:57 +0x47
2015/03/06 14:08:08 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:59 +0x108
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 77 [chan receive, 10 minutes]:
2015/03/06 14:08:08 packer-builder-openstack: code.google.com/p/go.crypto/ssh.(*forwardList).handleChannels(0xc2080d2250, 0xc20808c580)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/tcpip.go:178 +0x73
2015/03/06 14:08:08 packer-builder-openstack: created by code.google.com/p/go.crypto/ssh.NewClient
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/go/src/code.google.com/p/go.crypto/ssh/client.go:60 +0x15b
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 1527 [select]:
2015/03/06 14:08:08 packer-builder-openstack: net/http.(*persistConn).writeLoop(0xc208164370)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:885 +0x38f
2015/03/06 14:08:08 packer-builder-openstack: created by net/http.(*Transport).dialConn
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:601 +0x957
2015/03/06 14:08:08 packer-builder-openstack:
2015/03/06 14:08:08 packer-builder-openstack: goroutine 1526 [IO wait]:
2015/03/06 14:08:08 packer-builder-openstack: net.runtime_pollWait(0xa11a28, 0x72, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/netpoll.goc:146 +0x66
2015/03/06 14:08:08 packer-builder-openstack: net.(*pollDesc).Wait(0xc2080c54f0, 0x72, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
2015/03/06 14:08:08 packer-builder-openstack: net.(*pollDesc).WaitRead(0xc2080c54f0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
2015/03/06 14:08:08 packer-builder-openstack: net.(*netFD).Read(0xc2080c5490, 0xc20812f000, 0x1000, 0x1000, 0x0, 0xa10290, 0x23)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/fd_unix.go:242 +0x34c
2015/03/06 14:08:08 packer-builder-openstack: net.(*conn).Read(0xc2081900c0, 0xc20812f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/net.go:122 +0xe7
2015/03/06 14:08:08 packer-builder-openstack: net/http.noteEOFReader.Read(0xa128e8, 0xc2081900c0, 0xc2081643c8, 0xc20812f000, 0x1000, 0x1000, 0xc2080d4480, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:1203 +0x72
2015/03/06 14:08:08 packer-builder-openstack: net/http.(*noteEOFReader).Read(0xc208228c80, 0xc20812f000, 0x1000, 0x1000, 0xc208130170, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	<autogenerated>:124 +0xca
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).fill(0xc20817ba40)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:97 +0x1b3
2015/03/06 14:08:08 packer-builder-openstack: bufio.(*Reader).Peek(0xc20817ba40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/bufio/bufio.go:132 +0x101
2015/03/06 14:08:08 packer-builder-openstack: net/http.(*persistConn).readLoop(0xc208164370)
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:782 +0x95
2015/03/06 14:08:08 packer-builder-openstack: created by net/http.(*Transport).dialConn
2015/03/06 14:08:08 packer-builder-openstack: 	/Users/mitchellh/code/3rdparty/go/src/pkg/net/http/transport.go:600 +0x93f
2015/03/06 14:08:08 Builds completed. Waiting on interrupt barrier...
2015/03/06 14:08:08 waiting for all plugin processes to complete...
2015/03/06 14:08:08 /usr/local/bin/packer-builder-openstack: plugin process exited
2015/03/06 14:08:08 /usr/local/bin/packer-provisioner-ansible-local: plugin process exited
2015/03/06 14:08:08 /usr/local/bin/packer-provisioner-shell: plugin process exited
2015/03/06 14:08:08 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/03/06 14:08:08 /usr/local/bin/packer-provisioner-shell: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/mitchellh/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### LINKED ISSUE #2009: NPE in openstack.WaitForImage
If the Image struct returned from here: https://github.com/mitchellh/gophercloud-fork-40444fb/blob/40444fbc2b10960682b34e6822eb9179216e1ae1/images.go#L31 has a null Status field, WaitForImage throws an NPE here https://github.com/mitchellh/packer/blob/master/builder/openstack/step_create_image.go#L62.

#### Gist Log
https://gist.github.com/pmbauer/08ad2c7b1737ca3f4925

#### Packer template
```
{
    "builders": [
        {
            "type": "openstack",
            "ssh_username": "ubuntu",
            "image_name": "test",
            "source_image": "3209cbda-0fc3-453d-95b0-b28a69377c69",
            "flavor": "be3ea362-d7eb-4769-b91a-f7ca84a8b53e",
            "region": "RegionOne",
            "networks": ["9a45b413-7e6a-4146-948a-6fe08de2a535"]
        }
    ]
}
```

OpenStack deployment is Juno.

_*edit*_
This happens consistently and isn't specific to any particular image ID.  I suspect this very well may indicate an OpenStack bug as well (source of empty Status field).

### LINKED ISSUE #2102: Packer crash: unexpected EOF from OpenStack when deleting temporary keypair
Hi there -- I've just had a crash in version 0.7.5 of Packer when trying to create an image using OpenStack.  From the crash log, it looks like it happened when it got a 404 back from OpenStack when trying to delete the temporary keypair. 

I've uploaded a redacted version of the crash log at https://gist.github.com/saintaardvark/f8d85a74e9dde3b69b54; I've removed the output of the script being run on the image, but have tried to leave everything else in place.

Thanks, and please let me know if you need any further information

### LINKED ISSUE #2198: Packer OpenStack builder auth fails
When I attempt to build my image with the OpenStack builder on my private OpenStack, I get an error:

```bash
$ packer build -only=openstack template.json
openstack output will be in this color.

Build 'openstack' errored: Auth failed. Status code is: %!s(int=404).

==> Some builds didn't complete successfully and had errors:
--> openstack: Auth failed. Status code is: %!s(int=404).
```

I'm able to auth successfully through the OpenStack REST API:
```bash
$ source os_admin
[\u@\h \W(_OPENSTACK)]$ curl -s -X POST http://172.20.203.7:5000/v2.0/tokens \
>             -H "Content-Type: application/json" \
>             -d '{"auth": {"tenantName": "'"$OS_TENANT_NAME"'", "passwordCredentials":
quote>             {"username": "'"$OS_USERNAME"'", "password": "'"$OS_PASSWORD"'"}}}' | json
{
  "access": {
    "token": {
      "issued_at": "2015-06-09T18:34:00.450121",
      "expires": "2015-06-09T19:34:00Z",
      "id": "<hidden>",
      "tenant": {
        "description": "Admin Tenant",
        "enabled": true,
        "id": "573647cfe03349998dd3abc564e5e903",
        "name": "admin"
      },
      "audit_ids": [
        "N9bS7fLTRlWpNNPay6sLVw"
      ]
    },
    "serviceCatalog": [
      {
        "endpoints": [
          {
            "adminURL": "http://172.20.203.7:8774/v2/573647cfe03349998dd3abc564e5e903",
            "region": "regionOne",
            "internalURL": "http://172.20.203.7:8774/v2/573647cfe03349998dd3abc564e5e903",
            "id": "34fb332169ff4a619f60cb7817cbdbaf",
            "publicURL": "http://172.20.203.7:8774/v2/573647cfe03349998dd3abc564e5e903"
          }
        ],
        "endpoints_links": [],
        "type": "compute",
        "name": "nova"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://172.20.203.7:9696",
            "region": "regionOne",
            "internalURL": "http://172.20.203.7:9696",
            "id": "04f7855c76a24e92a1093f698b18c20a",
            "publicURL": "http://172.20.203.7:9696"
          }
        ],
        "endpoints_links": [],
        "type": "network",
        "name": "neutron"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://172.20.203.7:9292",
            "region": "regionOne",
            "internalURL": "http://172.20.203.7:9292",
            "id": "0391eb8f3d284a7cb2ddedf858665fa6",
            "publicURL": "http://172.20.203.7:9292"
          }
        ],
        "endpoints_links": [],
        "type": "image",
        "name": "glance"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://172.20.203.7:8000/v1",
            "region": "regionOne",
            "internalURL": "http://172.20.203.7:8000/v1",
            "id": "11fcdd20374a434d8f664c51905ab439",
            "publicURL": "http://172.20.203.7:8000/v1"
          }
        ],
        "endpoints_links": [],
        "type": "cloudformation",
        "name": "heat-cfn"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://172.20.203.7:8004/v1/573647cfe03349998dd3abc564e5e903",
            "region": "regionOne",
            "internalURL": "http://172.20.203.7:8004/v1/573647cfe03349998dd3abc564e5e903",
            "id": "8f1779627f2245bc99cf52634addb736",
            "publicURL": "http://172.20.203.7:8004/v1/573647cfe03349998dd3abc564e5e903"
          }
        ],
        "endpoints_links": [],
        "type": "orchestration",
        "name": "heat"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://172.20.203.7:35357/v2.0",
            "region": "regionOne",
            "internalURL": "http://172.20.203.7:5000/v2.0",
            "id": "03a74cc367ec43f88e2e9aee65edb1cf",
            "publicURL": "http://172.20.203.7:5000/v2.0"
          }
        ],
        "endpoints_links": [],
        "type": "identity",
        "name": "keystone"
      }
    ],
    "user": {
      "username": "admin",
      "roles_links": [],
      "id": "a923f3d9a4924c43b1bdac66ba51aad9",
      "roles": [
        {
          "name": "_member_"
        },
        {
          "name": "admin"
        }
      ],
      "name": "admin"
    },
    "metadata": {
      "is_admin": 0,
      "roles": [
        "3aa6be76656b422dab4f18a9fb0680f8",
        "b450456ba7a14be08bedd19817e21d6c"
      ]
    }
  }
}
[\u@\h \W(_OPENSTACK)]$
```

Below is the os_admin file I normally use with HEAT:
```
export OS_USERNAME=admin
export OS_TENANT_NAME=admin
export OS_PASSWORD=<hidden>
export OS_AUTH_URL=http://172.20.203.7:5000/v2.0/
export PS1='[\u@\h \W(_OPENSTACK)]\$ '
```

Below is the OpenStack builder in my Packer template.json.  I'm attempting to execute the builder behind my corporate VPN; I need the proxy so that provisioning can succeed.
```json
  "builders": [
    {
      "type": "openstack",
      "username": "admin",
      "password": "<hidden>",
      "provider": "http://172.20.203.7:5000/v2.0/",
      "openstack_provider": "openstack",
      "project": "admin",
      "networks": ["80a43c40-9940-466d-b276-4ee59e7a0332"],
      "proxy_url": "http://proxy.esl.cisco.com",
      "image_name": "centos-7-0-x64-openstack",
      "source_image": "622368bd-e974-48ef-addc-40d1a7699170",
      "flavor": "1",
      "insecure": true,
      "tenant_id": "573647cfe03349998dd3abc564e5e903"
    }    
  ]
```

Below is the debug output from the Packer command:
```bash
$ packer build -only=openstack template.json
2015/06/09 11:28:31 [INFO] Packer version: 0.7.5  9cd66feeacbd9cb318b72eb5ed59428c5b8c37ac+CHANGES
2015/06/09 11:28:31 Packer Target OS/Arch: darwin amd64
2015/06/09 11:28:31 Built with Go Version: go1.3.3
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: amazon-chroot = /usr/local/bin/packer-builder-amazon-chroot
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: amazon-ebs = /usr/local/bin/packer-builder-amazon-ebs
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: amazon-instance = /usr/local/bin/packer-builder-amazon-instance
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: digitalocean = /usr/local/bin/packer-builder-digitalocean
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: docker = /usr/local/bin/packer-builder-docker
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: googlecompute = /usr/local/bin/packer-builder-googlecompute
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: null = /usr/local/bin/packer-builder-null
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: openstack = /usr/local/bin/packer-builder-openstack
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: parallels-iso = /usr/local/bin/packer-builder-parallels-iso
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: parallels-pvm = /usr/local/bin/packer-builder-parallels-pvm
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: qemu = /usr/local/bin/packer-builder-qemu
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: virtualbox-iso = /usr/local/bin/packer-builder-virtualbox-iso
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: virtualbox-ovf = /usr/local/bin/packer-builder-virtualbox-ovf
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: vmware-iso = /usr/local/bin/packer-builder-vmware-iso
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: vmware-vmx = /usr/local/bin/packer-builder-vmware-vmx
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: atlas = /usr/local/bin/packer-post-processor-atlas
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: compress = /usr/local/bin/packer-post-processor-compress
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: docker-import = /usr/local/bin/packer-post-processor-docker-import
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: docker-push = /usr/local/bin/packer-post-processor-docker-push
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: docker-save = /usr/local/bin/packer-post-processor-docker-save
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: docker-tag = /usr/local/bin/packer-post-processor-docker-tag
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: vagrant = /usr/local/bin/packer-post-processor-vagrant
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: vagrant-cloud = /usr/local/bin/packer-post-processor-vagrant-cloud
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: vsphere = /usr/local/bin/packer-post-processor-vsphere
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: ansible-local = /usr/local/bin/packer-provisioner-ansible-local
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: chef-client = /usr/local/bin/packer-provisioner-chef-client
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: chef-solo = /usr/local/bin/packer-provisioner-chef-solo
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: file = /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: puppet-masterless = /usr/local/bin/packer-provisioner-puppet-masterless
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: puppet-server = /usr/local/bin/packer-provisioner-puppet-server
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: salt-masterless = /usr/local/bin/packer-provisioner-salt-masterless
2015/06/09 11:28:31 [DEBUG] Discoverd plugin: shell = /usr/local/bin/packer-provisioner-shell
2015/06/09 11:28:31 Detected home directory from env var: /Users/patrmurr
2015/06/09 11:28:31 Detected home directory from env var: /Users/patrmurr
2015/06/09 11:28:31 Attempting to open config file: /Users/patrmurr/.packerconfig
2015/06/09 11:28:31 File doesn't exist, but doesn't need to. Ignoring.
2015/06/09 11:28:31 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[amazon-chroot:/usr/local/bin/packer-builder-amazon-chroot amazon-instance:/usr/local/bin/packer-builder-amazon-instance null:/usr/local/bin/packer-builder-null vmware-iso:/usr/local/bin/packer-builder-vmware-iso vmware-vmx:/usr/local/bin/packer-builder-vmware-vmx amazon-ebs:/usr/local/bin/packer-builder-amazon-ebs docker:/usr/local/bin/packer-builder-docker openstack:/usr/local/bin/packer-builder-openstack digitalocean:/usr/local/bin/packer-builder-digitalocean virtualbox-iso:/usr/local/bin/packer-builder-virtualbox-iso virtualbox-ovf:/usr/local/bin/packer-builder-virtualbox-ovf googlecompute:/usr/local/bin/packer-builder-googlecompute parallels-iso:/usr/local/bin/packer-builder-parallels-iso parallels-pvm:/usr/local/bin/packer-builder-parallels-pvm qemu:/usr/local/bin/packer-builder-qemu] PostProcessors:map[atlas:/usr/local/bin/packer-post-processor-atlas docker-import:/usr/local/bin/packer-post-processor-docker-import docker-push:/usr/local/bin/packer-post-processor-docker-push docker-save:/usr/local/bin/packer-post-processor-docker-save docker-tag:/usr/local/bin/packer-post-processor-docker-tag vagrant:/usr/local/bin/packer-post-processor-vagrant compress:/usr/local/bin/packer-post-processor-compress vagrant-cloud:/usr/local/bin/packer-post-processor-vagrant-cloud vsphere:/usr/local/bin/packer-post-processor-vsphere] Provisioners:map[ansible-local:/usr/local/bin/packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-provisioner-chef-client chef-solo:/usr/local/bin/packer-provisioner-chef-solo file:/usr/local/bin/packer-provisioner-file puppet-masterless:/usr/local/bin/packer-provisioner-puppet-masterless puppet-server:/usr/local/bin/packer-provisioner-puppet-server salt-masterless:/usr/local/bin/packer-provisioner-salt-masterless shell:/usr/local/bin/packer-provisioner-shell]}
2015/06/09 11:28:31 Setting cache directory: /Users/patrmurr/code/apps/mdp-sdk/packer_templates/centos-7.0/packer_cache
2015/06/09 11:28:31 Detected home directory from env var: /Users/patrmurr
2015/06/09 11:28:31 Reading template: template.json
2015/06/09 11:28:31 Skipping build 'virtualbox-iso' because not specified by -only.
2015/06/09 11:28:31 Creating build: openstack
2015/06/09 11:28:31 Loading builder: openstack
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-builder-openstack
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-builder-openstack []string{"/usr/local/bin/packer-builder-openstack"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-builder-openstack
2015/06/09 11:28:31 packer-builder-openstack: 2015/06/09 11:28:31 Plugin minimum port: 10000
2015/06/09 11:28:31 packer-builder-openstack: 2015/06/09 11:28:31 Plugin maximum port: 25000
2015/06/09 11:28:31 packer-builder-openstack: 2015/06/09 11:28:31 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin045716094
2015/06/09 11:28:31 packer-builder-openstack: 2015/06/09 11:28:31 Waiting for connection...
2015/06/09 11:28:31 packer-builder-openstack: 2015/06/09 11:28:31 Serving a plugin connection...
2015/06/09 11:28:31 Loading provisioner: file
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin minimum port: 10000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin maximum port: 25000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin305305294
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Waiting for connection...
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Serving a plugin connection...
2015/06/09 11:28:31 Loading provisioner: file
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin minimum port: 10000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin maximum port: 25000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin584250573
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Waiting for connection...
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Serving a plugin connection...
2015/06/09 11:28:31 Loading provisioner: file
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin minimum port: 10000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin maximum port: 25000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin799885201
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Waiting for connection...
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Serving a plugin connection...
2015/06/09 11:28:31 Loading provisioner: file
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin minimum port: 10000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin maximum port: 25000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin132269728
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Waiting for connection...
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Serving a plugin connection...
2015/06/09 11:28:31 Loading provisioner: file
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin minimum port: 10000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin maximum port: 25000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin474001461
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Waiting for connection...
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Serving a plugin connection...
2015/06/09 11:28:31 Loading provisioner: file
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin minimum port: 10000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin maximum port: 25000
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin731555873
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Waiting for connection...
2015/06/09 11:28:31 packer-provisioner-file: 2015/06/09 11:28:31 Serving a plugin connection...
2015/06/09 11:28:31 Loading provisioner: file
2015/06/09 11:28:31 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:31 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:31 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Plugin minimum port: 10000
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Plugin maximum port: 25000
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin611370834
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Waiting for connection...
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Serving a plugin connection...
2015/06/09 11:28:32 Loading provisioner: file
2015/06/09 11:28:32 Creating plugin client for path: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:32 Starting plugin: /usr/local/bin/packer-provisioner-file []string{"/usr/local/bin/packer-provisioner-file"}
2015/06/09 11:28:32 Waiting for RPC address for: /usr/local/bin/packer-provisioner-file
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Plugin minimum port: 10000
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Plugin maximum port: 25000
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin204478273
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Waiting for connection...
2015/06/09 11:28:32 packer-provisioner-file: 2015/06/09 11:28:32 Serving a plugin connection...
2015/06/09 11:28:32 Loading provisioner: shell
2015/06/09 11:28:32 Creating plugin client for path: /usr/local/bin/packer-provisioner-shell
2015/06/09 11:28:32 Starting plugin: /usr/local/bin/packer-provisioner-shell []string{"/usr/local/bin/packer-provisioner-shell"}
2015/06/09 11:28:32 Waiting for RPC address for: /usr/local/bin/packer-provisioner-shell
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Plugin minimum port: 10000
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Plugin maximum port: 25000
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin190492025
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Waiting for connection...
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Serving a plugin connection...
2015/06/09 11:28:32 Loading provisioner: shell
2015/06/09 11:28:32 Creating plugin client for path: /usr/local/bin/packer-provisioner-shell
2015/06/09 11:28:32 Starting plugin: /usr/local/bin/packer-provisioner-shell []string{"/usr/local/bin/packer-provisioner-shell"}
2015/06/09 11:28:32 Waiting for RPC address for: /usr/local/bin/packer-provisioner-shell
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Plugin minimum port: 10000
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Plugin maximum port: 25000
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Plugin address: unix /var/folders/4_/xwr0_2q9755_c_m2gnlv16lr0000gp/T/packer-plugin183293017
openstack output will be in this color.
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Waiting for connection...
2015/06/09 11:28:32 packer-provisioner-shell: 2015/06/09 11:28:32 Serving a plugin connection...
2015/06/09 11:28:32 ui: openstack output will be in this color.
2015/06/09 11:28:32 ui:
2015/06/09 11:28:32 Build debug mode: false
2015/06/09 11:28:32 Force build: false
2015/06/09 11:28:32 Preparing build: openstack
2015/06/09 11:28:32 packer-builder-openstack: 2015/06/09 11:28:32 Config: {PackerConfig:{PackerBuildName:openstack PackerBuilderType:openstack PackerDebug:false PackerForce:false PackerUserVars:map[]} AccessConfig:{Username:admin Password:<Filtered> ApiKey: Project:admin Provider:http://172.20.203.7:5000/v2.0/ RawRegion: ProxyUrl:http://proxy.esl.cisco.com TenantId:573647cfe03349998dd3abc564e5e903 Insecure:true} ImageConfig:{ImageName:centos-7-0-x64-openstack} RunConfig:{SourceImage:622368bd-e974-48ef-addc-40d1a7699170 Flavor:1 RawSSHTimeout:5m SSHUsername:root SSHPort:22 OpenstackProvider:openstack UseFloatingIp:false FloatingIpPool: FloatingIp: SecurityGroups:[] Networks:[80a43c40-9940-466d-b276-4ee59e7a0332] sshTimeout:300000000000} tpl:0xc2080a1ac0}
2015/06/09 11:28:32 Waiting on builds to complete...
2015/06/09 11:28:32 Starting build run: openstack
2015/06/09 11:28:32 Running builder: openstack

2015/06/09 11:31:02 ui error: Build 'openstack' errored: Auth failed. Status code is: %!s(int=404).
2015/06/09 11:31:02 Builds completed. Waiting on interrupt barrier...
2015/06/09 11:31:02 machine readable: error-count []string{"1"}
2015/06/09 11:31:02 ui error:
==> Some builds didn't complete successfully and had errors:
2015/06/09 11:31:02 machine readable: openstack,error []string{"Auth failed. Status code is: %!s(int=404)."}
2015/06/09 11:31:02 ui error: --> openstack: Auth failed. Status code is: %!s(int=404).
2015/06/09 11:31:02 ui:
==> Builds finished but no artifacts were created.
2015/06/09 11:31:02 waiting for all plugin processes to complete...
Build 'openstack' errored: Auth failed. Status code is: %!s(int=404).

==> Some builds didn't complete successfully and had errors:
--> openstack: Auth failed. Status code is: %!s(int=404).

==> Builds finished but no artifacts were created.
2015/06/09 11:31:02 /usr/local/bin/packer-builder-openstack: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-shell: plugin process exited
2015/06/09 11:31:02 /usr/local/bin/packer-provisioner-shell: plugin process exited
```

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #2198 
Fixes #2102 
Fixes #2009 
Fixes #1966 
Fixes #1785 
Fixes #1472 
Fixes #1626 

**NOTE: AUTH IS BACKWARDS INCOMPATIBLE** The silver lining though is that the OpenStack provider _just works_ with the proper env vars, which I think is how most people are configuring anyways. Also, the old env vars are backwards compat.

This just throws away our old OpenStack builder and replaces it with a new one based on the more or less official gophercloud client. We redid the auth since I wasn't sure how a lot of the old auth carries over. I'll note this in the CHANGELOG after merge.

I added a basic acceptance test that passes but requires a lot of env vars. :)

:construction: I'm still making some changes here (specifically to remove the old client), but it should be ready for review regardless.

Tested with:

* [Vexxhost](http://vexxhost.com)
* RackSpace

### CODE REVIEW

File: builder/openstack/step_allocate_ip.go [hunk 1]
```diff
@@ -15,53 +16,78 @@ type StepAllocateIp struct {
...
 
-	var instanceIp gophercloud.FloatingIp
+	var instanceIp *floatingip.FloatingIP
 	// This is here in case we error out before putting instanceIp into the
 	// statebag below, because it is requested by Cleanup()
 	state.Put("access_ip", instanceIp)
 
 	if s.FloatingIp != "" {
-		instanceIp.Ip = s.FloatingIp
+		*instanceIp = floatingip.FloatingIP{FixedIP: s.FloatingIp}
```
Comment (einarf) [inline builder/openstack/step_allocate_ip.go]: Will crash (nil pointer dereference)

File: builder/openstack/step_allocate_ip.go [hunk 2]
```diff
@@ -15,53 +16,78 @@ type StepAllocateIp struct {
...
 		if err != nil {
 			err := fmt.Errorf("Error creating floating ip from pool '%s'", s.FloatingIpPool)
 			state.Put("error", err)
 			ui.Error(err.Error())
 			return multistep.ActionHalt
 		}
-		instanceIp = newIp
-		ui.Say(fmt.Sprintf("Created temporary floating IP %s...", instanceIp.Ip))
+
+		*instanceIp = *newIp
```
Comment (einarf) [inline builder/openstack/step_allocate_ip.go]: Will crash (nil pointer dereference)

File: builder/openstack/step_allocate_ip.go [hunk 3]
```diff
@@ -15,53 +16,78 @@ type StepAllocateIp struct {
...
+		ui.Say(fmt.Sprintf("Created temporary floating IP %s...", instanceIp.FixedIP))
 	}
 
-	if instanceIp.Ip != "" {
-		if err := csp.AssociateFloatingIp(server.Id, instanceIp); err != nil {
-			err := fmt.Errorf("Error associating floating IP %s with instance.", instanceIp.Ip)
+	if instanceIp != nil && instanceIp.FixedIP != "" {
```
Comment (einarf) [inline builder/openstack/step_allocate_ip.go]: FixedIP is only set if you supplied in IP through `floating_ip`. If an IP is retuned from the pool it will be set in the IP field. This means that the instance will not get its IP allocated if it's fetched from the pool.

Comment (mitchellh) [inline builder/openstack/step_allocate_ip.go]: Good catch.

**Comment by mitchellh** [comment]
Reviewed/tested by some Packer community, bringing it in!

**Comment by m1keil** [comment]
awesome!!!

**Comment by einarf** [comment]
Also did quite a bit of testing on identity v3.

For server configuration...
* Works when fetching IP from pool (`floating_ip_pool`)
* Works when specifying an existing floating IP assigned to the project (`floating_ip`)
* Works when specifying network id

**Comment by einarf** [comment]
You might want to mention in the changelog that the opentstack builder now supports identity v3. A lot of people (at least in my community) have been waiting for this. It means that packer now supports all those new small public and private clouds that are popping up everywhere.
