### PR TITLE
helper/config: copy buildname/buildtype properly

### LINKED ISSUE #2363: Unable to use build_name function in template with Packer v0.8.0
Hi, I'm trying to use the `build_name`/`build_type` functions that were introduced with v0.8.0, but I always receive a message saying that it is not available. Example:

    $ cat test.json
    {
      "builders": [{
        "type": "amazon-ebs",
        "region": "us-east-1",
        "source_ami": "ami-c65be9ae",
        "instance_type": "t1.micro",
        "ssh_username": "ubuntu",
        "ami_name": "packer-example {{timestamp}}"
      }],
      "provisioners": [{
        "type": "shell-local",
        "command": "echo {{build_type}}"
      }]
    }
    $ packer validate test.json 
    Template validation failed. Errors are shown below.

    Errors validating build 'amazon-ebs'. render 'command': template: root:1:7: executing "root" at <build_type>: error calling build_type: build_name not available in:

    echo {{build_type}}

Substituting `pwd` or `timestamp` validates successfully. I get the same behaviour with CentOS 7.1.1503 and OS X 10.10.3.

Somewhat related, I think line 74 of `template/interpolate/funcs.go` should reference `build_type` instead of `build_name`.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #2363 

We were forgetting to set the build name and build type for existing contexts. I'm going to add tests now but the logic is there.

### CODE REVIEW

File: template/interpolate/funcs.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func funcGenBuildName(ctx *Context) interface{} {
 func funcGenBuildType(ctx *Context) interface{} {
 	return func() (string, error) {
 		if ctx == nil || ctx.BuildType == "" {
-			return "", errors.New("build_name not available")
+			return "", errors.New("build_type not available")
```
Comment (mitchellh) [inline template/interpolate/funcs.go]: This was just a random oversight.

**Comment by cbednarski** [comment]
:+1:

**Comment by mitchellh** [comment]
Added the tests.
