### PR TITLE
Validate capture variables to obey Azure's rules.

### LINKED ISSUE #3535: Azure Build Should Validate capture_container_name and capture_name_prefix Variables
The Azure builder does not validate that the variables *capture_container_name* and *capture_name_prefix* respect Azure's naming rules.

| Name | Rule Description |
| ------- | -------------------- | 
| capture_container_name | Container names may only contain lowercase letters, numbers, and hyphens, and must begin with a letter or a number.  The name cannot contain two consecutive hyphens.  The name must also be between 3 and 64 characters long. |
| capture_name_prefix| A valid prefix begins with an alphanumeric characters, then 0 or up to 23 alphanumeric characters, hyphens, periods, or underscores.  The prefix cannot contain two consecutive hypens. |

The API returns a regular expression in the error message, so I'm including it for completeness.

| Name | Regular Expression |
| ------- | -------------------- | 
| capture_container_name | ^[\w][\w-]{2,62}(?<![-.])$ |
| capture_name_prefix |  ^[^_\\\\W][\\\\w-\\._]{0,23}(?<![-.])$ |

### LINKED ISSUE #3551: azure's blob name must be 23 character long
I ended myself in a situation where the "capuring image" was unable to finish because the name f48sn-workbench-1463594889 was too long.  response is very confusing unless PACKER_LOG is enabled. 

please review the sanity check of  capture_name_prefix accordingly so this error can be spotted early on 

```
2016/05/18 18:25:09 packer: 2016/05/18 18:25:09 Azure request method="POST" request="https://management.azure.com/subscriptions/594bef42-33f3-42df-b056-e7399d6ae7a0/resourceGroups/packer-Resource-Group-16z9420dw1/providers/Microsoft.Compute/virtualMachines/pkrvm16z9420dw1/generalize?api-version=2015-06-15" body=""
2016/05/18 18:25:10 packer: 2016/05/18 18:25:10 Azure response status="200 OK" method="POST" request="https://management.azure.com/subscriptions/594bef42-33f3-42df-b056-e7399d6ae7a0/resourceGroups/packer-Resource-Group-16z9420dw1/providers/Microsoft.Compute/virtualMachines/pkrvm16z9420dw1/generalize?api-version=2015-06-15" x-ms-request-id="6c00d668-37b0-4a41-a935-abda3fdfe99b" body=""
2016/05/18 18:25:10 packer: 2016/05/18 18:25:10 Azure response status="200 OK" method="POST" request="https://management.azure.com/subscriptions/594bef42-33f3-42df-b056-e7399d6ae7a0/resourceGroups/packer-Resource-Group-16z9420dw1/providers/Microsoft.Compute/virtualMachines/pkrvm16z9420dw1/generalize?api-version=2015-06-15" x-ms-request-id="6c00d668-37b0-4a41-a935-abda3fdfe99b" body=""
2016/05/18 18:25:10 packer: 2016/05/18 18:25:10 Azure request method="POST" request="https://management.azure.com/subscriptions/594bef42-33f3-42df-b056-e7399d6ae7a0/resourceGroups/packer-Resource-Group-16z9420dw1/providers/Microsoft.Compute/virtualMachines/pkrvm16z9420dw1/capture?api-version=2015-06-15" body="{\"vhdPrefix\":\"f48sn-workbench-1463594889\",\"destinationContainerName\":\"images\",\"overwriteVhds\":false}"
2016/05/18 18:25:10 packer: 2016/05/18 18:25:10 Azure response status="400 Bad Request" method="POST" request="https://management.azure.com/subscriptions/594bef42-33f3-42df-b056-e7399d6ae7a0/resourceGroups/packer-Resource-Group-16z9420dw1/providers/Microsoft.Compute/virtualMachines/pkrvm16z9420dw1/capture?api-version=2015-06-15" x-ms-request-id="66794f59-7dfb-4224-bdaa-4c6a9b7ebeb1" body="{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"vhdPrefix\",\r\n    \"message\": \"'f48sn-workbench-1463594889' is not a valid captured VHD blob name prefix. A valid prefix matches regex '^[^_\\\\W][\\\\w-._]{0,23}(?<![-.])$'.\"\r\n  }\r\n}"
2016/05/18 18:25:10 ui error: ==> azure-arm: azure#updatePollingState: Azure Polling Error - Unable to obtain polling URI for POST : StatusCode=0
==> azure-arm: azure#updatePollingState: Azure Polling Error - Unable to obtain polling URI for POST : StatusCode=0
```

- Packer Version: 0.10.1
- Host platform: GNU/Linux 3.2.0-4-amd64 Debian 3.2.65-1+deb7u1 x86_64

### PR DESCRIPTION
**Pull request by boumenot**
This PR validates that capture_name_prefix and capture_container_name follow Azure's naming rules.

Closes #3535 
Closes #3551

### CODE REVIEW

**Comment by boumenot** [comment]
Closes #3551

File: builder/azure/arm/config.go [hunk 1]
```diff
@@ -392,11 +393,33 @@ func assertRequiredParametersSet(c *Config, errs *packer.MultiError) {
 	/////////////////////////////////////////////
 	// Capture
 	if c.CaptureContainerName == "" {
-		errs = packer.MultiErrorAppend(errs, fmt.Errorf("An capture_container_name must be specified"))
+		errs = packer.MultiErrorAppend(errs, fmt.Errorf("A capture_container_name must be specified"))
+	}
+
+	captureContainerNameRegex := regexp.MustCompile("^[a-z0-9][a-z0-9\\-]{2,62}$")
```
Comment (cbednarski) [inline builder/azure/arm/config.go]: Style tip: I put `regexp.MustCompile` declarations at package scope (not inside a function) because that way they will be checked at compile time instead of runtime. To follow the pattern used elsewhere this should be named `reCaptureContainerName`.

File: builder/azure/arm/config.go [hunk 2]
```diff
@@ -392,11 +393,33 @@ func assertRequiredParametersSet(c *Config, errs *packer.MultiError) {
...
+	if !captureContainerNameRegex.MatchString(c.CaptureContainerName) {
+		errs = packer.MultiErrorAppend(errs, fmt.Errorf("A capture_container_name must satisfy the regular expression '^[a-z0-9][a-z0-9\\-]{2,62}$'."))
```
Comment (cbednarski) [inline builder/azure/arm/config.go]: To DRY the code you can use `captureContainerNameRegex.String()` to get the source text. This way it stays in sync if the pattern is updated later.

File: builder/azure/arm/config.go (hunk 1 above)
Comment (boumenot) [inline builder/azure/arm/config.go]: Nice!

File: builder/azure/arm/config.go (hunk 2 above)
Comment (boumenot) [inline builder/azure/arm/config.go]: Double nice!

**Comment by cbednarski** [comment]
LGTM!
