### PR TITLE
Ansible: add the support for specifying ansible_user

### LINKED ISSUE #3273: Ansible Remote ansible_ssh_user is packer-ansible
When using packer with ansible remote as the provisioner, the builtin ansible variable `ansible_ssh_user` (`ansible_user` for Ansible 2.0) is set to "packer-ansible". 

This means that playbooks that use {{ ansible_ssh_user }} in their playbooks will fail when the "packer-ansible" user is not found and they are expecting something like "ubuntu" in its place. 

```
    amazon-ebs: TASK [deploy : Create virtualenv directory] *******************************
==> amazon-ebs: starting sftp subsystem
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: failed to look up user packer-ansible", "owner": "root", "path": "/opt/app", "size": 4096, "state": "directory", "uid": 0}
```
packer.json provision snippet:
```
  "provisioners" : [
    {
      "type": "ansible",
      "playbook_file": "ansible/site.yml",
      "extra_arguments": [
        "--extra-vars",
        "\"provision_type=pilot revision={{user `revision`}}\""
      ]
    }
  ]
```

Steps to reproduce:  
Create a quick playbook and provision with packer. I used the amazon-ebs in my example. 
```
- name: Create virtualenv directory
  file: path=/opt/app/env state=directory owner={{ansible_user}} group={{ansible_user}} mode=0775 recurse=yes
  sudo: yes
```

I believe this is due to how packer does the ansible remote provision with an ssh proxy.
```
    amazon-ebs: SSH proxy: accepted connection
==> amazon-ebs: authentication attempt from 127.0.0.1:48350 to 127.0.0.1:45959 as packer-ansible using none
==> amazon-ebs: authentication attempt from 127.0.0.1:48350 to 127.0.0.1:45959 as packer-ansible using publickey
```

Packer version: `0.9.0`
Host OS: `Linux Arch-Linux 4.4.1-2-ARCH`

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Closes #3273

### CODE REVIEW

File: scripts/build.sh [hunk 1]
```diff
@@ -35,6 +35,7 @@ mkdir -p bin/
 echo "==> Building..."
 set +e
 gox \
+    -cgo \
```
Comment (rickard-von-essen) [inline scripts/build.sh]: @cbednarski Needed because ```os/user.Current()``` doesn't work without CGO. :scream:

Comment (cbednarski) [inline scripts/build.sh]: cgo breaks cross-compilation so I'd like to avoid this.

Comment (rickard-von-essen) [inline scripts/build.sh]: @cbednarski Changed to user env var ```$USER```. If you have a win machine can you test that env var ```%USER%``` is set to your username? (I only have posix machines available)

Comment (cbednarski) [inline scripts/build.sh]: Looks like we need `%USERNAME%` on Windows.

File: provisioner/ansible/provisioner.go [hunk 2]
```diff
@@ -111,6 +112,13 @@ func (p *Provisioner) Prepare(raws ...interface{}) error {
 		p.config.LocalPort = "0"
 	}
 
+	if p.config.User == "" {
+		p.config.User = os.ExpandEnv("${USER}")
```
Comment (cbednarski) [inline provisioner/ansible/provisioner.go]: Curious why you used `os.ExpandEnv("${USER}")` rather than `os.Getenv("USER")` here. ExpandEnv uses Getenv under the hood -- do we need the side effects of expand for something?

Comment (cbednarski) [inline provisioner/ansible/provisioner.go]: Also commented on the previous commit I think this needs to be %USERNAME% on Windows. I got a VM from here: https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/

Comment (rickard-von-essen) [inline provisioner/ansible/provisioner.go]: Just remembered we can ignore Windows in this case since [it is not supported to run the _Controller_ on a Windows host](http://docs.ansible.com/ansible/intro_windows.html#reminder-you-must-have-a-linux-control-machine).

Comment (rickard-von-essen) [inline provisioner/ansible/provisioner.go]: I have no reason choosing ExpandEnv over Getenv.
