### PR TITLE
builder/virtualbox: remove guest additions

### LINKED ISSUE #3652: virtualbox-iso with guest_additions_mode attach doesn't remove both virtual optical drives
When building a Windows based Packer box, uploading the virtualbox additions over WinRM frequently fails. To work around this you can either download the ISO from a network/internet location from within the VM, or you can choose the attach option. Using attach adds a second virtual optical drive in addition to the drive where the OS is being installed from, and when the packaging is complete one optical drive remains attached rather than zero. If Packer operated correctly I would expect undoing the addition of the installer ISO AND the tools ISO.
- Packer Version 0.10.1
- Host platform Windows 7

This occurs using mwrock/packer-templates and boxcutter/windows and using the attach option.

### PR DESCRIPTION
**Pull request by mwhooker**
closes #3652

### CODE REVIEW

File: builder/virtualbox/common/step_attach_guest_additions.go [hunk 1]
```diff
@@ -77,7 +77,7 @@ func (s *StepAttachGuestAdditions) Cleanup(state multistep.StateBag) {
 		"--medium", "none",
 	}
 
-	if err := driver.VBoxManage(command...); err != nil {
-		ui.Error(fmt.Sprintf("Error unregistering guest additions: %s", err))
-	}
+	// Remove the ISO. Note that this will probably fail since
```
Comment (DanHam) [inline builder/virtualbox/common/step_attach_guest_additions.go]: It would be nice if we could avoid this. We already see an error message generated by the clean up [here](https://github.com/mitchellh/packer/blob/master/builder/virtualbox/iso/step_attach_iso.go#L89-L91). This caused me some concern when I first saw it as there is no mention that it is safe to ignore. The error looks very similar to those seen in #4432.

Could we not update the state bag in step_remove_devices.go e.g. ```state.Put("guest_additions_attached", false)``` and then wrap an appropriate conditional around the code in step_attach_guest_additions.go to avoid the error?

Alternatively, would you consider an upstream addition to github.com/mitchellh/multistep that allows you to remove items from the state bag once they are no longer of any use? This would allow us to use the new method to: 

```
state.Remove("guest_additions_attached")
``` 

within step_remove_devices.go and use the same conditional logic within step_attach_guest_additions.go to avoid running the command if the guest additions have already been detached. e.g.

```
if _, ok := state.GetOk("guest_additions_attached"); ok {
...
}
```

I've already tested doing just this (with the required changes to the upstream multistep code) and it seems to work quite well. If you think this would be of any benefit let me know and I'll issue the required PR's for you to take a look at.

Cheers

Comment (mwhooker) [inline builder/virtualbox/common/step_attach_guest_additions.go]: > It would be nice if we could avoid this. 

what do you mean by `this`?

This is effectively a no-op if the iso has already been detached (as from step_remove_devices)

Comment (mwhooker) [inline builder/virtualbox/common/step_attach_guest_additions.go]: oh, you mean the debug logs from the driver.vboxmanage? hmm, those aren't really supposed to be user facing, but I guess if you're trying to debug it could lead to some confusion. 

I think the complexity introduced by mutating state or checking for different flags is a more costly alternative than having some erroneous debug logs.

Comment (DanHam) [inline builder/virtualbox/common/step_attach_guest_additions.go]: > oh, you mean the debug logs from the driver.vboxmanage?

Right! Apologies for not making that obvious above. An example of what I'm on about can be seen in the log below. Clearly the first VBoxManage command is from step_remove_devices while the next one (with the error message) is from the clean up in step_attach_guest_additions.

```
2017/01/30 17:10:21 ui: ==> virtualbox-iso: Gracefully halting virtual machine...
...
2017/01/30 17:10:23 packer: 2017/01/30 17:10:23 VM shut down.
2017/01/30 17:10:23 packer: 2017/01/30 17:10:23 Executing VBoxManage: []string{"storageattach", "centos-7-x86_64", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2017/01/30 17:10:23 packer: 2017/01/30 17:10:23 stdout:
2017/01/30 17:10:23 packer: 2017/01/30 17:10:23 stderr:
...
2017/01/30 17:10:24 ui: ==> virtualbox-iso: Preparing to export machine...
...
...
2017/01/30 17:11:02 packer: 2017/01/30 17:11:02 Executing VBoxManage: []string{"storageattach", "centos-7-x86_64", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2017/01/30 17:11:02 packer: 2017/01/30 17:11:02 stdout:
2017/01/30 17:11:02 packer: 2017/01/30 17:11:02 stderr: VBoxManage: error: No storage device attached to device slot 1 on port 0 of controller 'IDE Controller'
2017/01/30 17:11:02 packer: VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee nsISupports
2017/01/30 17:11:02 packer: VBoxManage: error: Context: "DetachDevice(Bstr(pszCtl).raw(), port, device)" at line 393 of file VBoxManageStorageController.cpp
2017/01/30 17:11:02 ui: ==> virtualbox-iso: Unregistering and deleting virtual machine...
...
```

It's only *after* having poked around in the source code that I now know where this error is coming from, and that it can safely be ignored. However, when I was looking at this before (from the standpoint of an end user) the message worried me - What was going wrong to cause this message? I guess this is about end user perception...

My concern is that at the end of a Packer build there is the possibility of a bunch of errors appearing in the logs and no clear indication of where they are coming from or that they are safe to ignore. This is why I was hoping we could somehow avoid running the detach command again in the clean up phase.

Comment (DanHam) [inline builder/virtualbox/common/step_attach_guest_additions.go]: Quick questions:

```if _, ok := state.GetOk("guest_additions_attached"); ok {```

`ok` would evaluate to true even if we have previously set `state.Put("guest_additions_attached", false)`. Shouldn't the *result* returned by `GetOk` be used here as well/instead?

> I think the complexity introduced by mutating state...

I kind of get where you're coming from, but isn't tracking the changing state through all the steps the point of the state bag? ;)

As always, feedback/explanations helping me to understand all this are much appreciated!

Comment (mwhooker) [inline builder/virtualbox/common/step_attach_guest_additions.go]: we're not setting `guest_additions_attached` to anything in particular, just using it as a sentinel value.

We do use the state bag to maintain state, but we don't mutate it, in general. Setting an additional flag for each device we've already tried to detach sounds fine, and will accept PRs for that.

I think the way that I'd like to see this done is to create a new class called something like `VBoxDevice` which holds all the data in the `storageattach` command. We'd set this in the state: `state.Put("guest_additions_device", &VBoxDevice{...})`.

We'd then add two methods to the driver: `AttachDevice` and `DetachDevice`. `DetachDevice` could consult a flag/`sync.once` object to make sure we only detached once.

I think this would be a fun thing to write, and would make the code simpler, but I don't have bandwidth. Will happily look at a PR if you make those changes.
