### PR TITLE
Update AWS EBS builder to fix invalid params

### LINKED ISSUE #2195: Can't create volume from snapshot for HVM EBS source AMI
Trying to build an AMI using the Ubuntu AMI [ami-3f176c05](https://console.aws.amazon.com/ec2/home?region=ap-southeast-2#launchAmi=ami-3f176c05) as the source. However when trying to attach a volume created from a snapshot I get the following error:

```
Build 'amazon-ebs' errored: Error launching source instance: InvalidParameterCombination: The parameter iops is not supported for standard volumes.
        status code: 400, request id: []
```

As far as I can tell this should be supported? It works for a PV EBS source AMI, and if I remove the ` "launch_block_device_mappings"` key it works fine.

Main builder config is:

```
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "ap-southeast-2",
      "source_ami": "ami-3f176c05",
      "instance_type": "t2.medium",
      "ssh_username": "ubuntu",
      "ami_name": "OpenVPN Ubuntu 14.04 LTS {{isotime | clean_ami_name}}",
      "ami_description": "OpenVPN Ubuntu 14.04 AMI",
      "iam_instance_profile": "...",
      "vpc_id": "...",
      "subnet_id": "...",
      "associate_public_ip_address": true,
      "launch_block_device_mappings": [{
        "device_name": "/dev/xvdf",
        "snapshot_id": "...",
        "delete_on_termination": true,
        "volume_type": "standard"
      }]
    }
  ]
```

I'm using packer compiled from source @ edf3415 as I needed some fixes.

### PR DESCRIPTION
**Pull request by catsby**
- `IOPS` is not a valid Block Device parameter if you're using `standard` or `gp2`
- `encrypted` is not valid if you're specifying a `snapshot_id`

Fixes #2195

### CODE REVIEW

File: builder/amazon/common/block_device_test.go [hunk 1]
```diff
@@ -48,11 +69,11 @@ func TestBlockDevice(t *testing.T) {
 		expected := []*ec2.BlockDeviceMapping{tc.Result}
 		got := blockDevices.BuildAMIDevices()
 		if !reflect.DeepEqual(expected, got) {
-			t.Fatalf("bad: %#v", expected)
+			t.Fatalf("Bad block device, \nexpected: %s\n\ngot: %s", awsutil.StringValue(expected), awsutil.StringValue(got))
```
Comment (cbednarski) [inline builder/amazon/common/block_device_test.go]: :heart: these descriptive error messages!

**Comment by cbednarski** [comment]
LGTM

**Comment by Soliah** [comment]
Thanks for this. This now requires that `volume_type` be set to something whereas the behaviour before was to default to "standard" I believe? Is this a documentation issue or should defaults be set?

**Comment by catsby** [comment]
@Soliah sorry, I'm not seeing anything in recent history that suggests there was ever a default, but I'm new to the codebase so I'll just have to take your word for it :smile: 

I'm also not really sure if `standard` is a reasonable default. It makes sense to me that it would be something specified explicitly.

**Comment by Soliah** [comment]
@catsby it may have not been an explicit default, but perhaps implicitly chosen by AWS when gp2 wasn't around . I haven't updated my packer templates for awhile and I definitely wasn't specifying the `volume_type`.

So this should probably just be updated in the docs indicating that it's required now.

**Comment by catsby** [comment]
@Soliah ah, I missed that AWS defaults to `standard` when `VolumeType` is omitted. Fortunately @janschumann fixed that in https://github.com/mitchellh/packer/pull/2201 :smile:
