### PR TITLE
Only Delete the Resource Group if the Resource Group Exists

### LINKED ISSUE #3515: Innocuous but Annoying Message: "Error deleting resource group. Please delete it manually."
This is against v0.10.1.

The Azure builder output this message at the end of a build.

```text
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Error deleting resource group.  Please delete it manually.
==> azure-arm:
==> azure-arm: Name: packer-Resource-Group-wmll9s4ps6
==> azure-arm: Error: azure#updatePollingState: Azure Polling Error - Unable to obtain polling URI for DELETE : StatusCode=0
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' finished.
```

I missed this, and I should not have.  Packer executes clean up at the end of a build, and the code does not properly handle a *clean* shutdown.  The code explicitly cleans up the resource group at the end of a build, but it also implements the cleanup method to ensure a resource group is deleted.  The cleanup method does not handle being called unnecessarily. What is the best (intended) way to handle this?

 1. The code should implement an explicit cleanup step, and ensure the cleanup method takes no action unless necessary.
 1. The code should **not** implement an explicit cleanup step.

### PR DESCRIPTION
**Pull request by boumenot**
Closes #3515

### CODE REVIEW

File: builder/azure/arm/step_delete_resource_group_test.go [hunk 1]
```diff
@@ -49,35 +49,32 @@ func TestStepDeleteResourceGroupShouldPassIfDeletePasses(t *testing.T) {
 	}
 }
 
-func TestStepDeleteResourceGroupShouldTakeStepArgumentsFromStateBag(t *testing.T) {
-	var actualResourceGroupName string
-
+func TestStepDeleteResourceGroupShouldDeleteStateBagArmResourceGroupCreated(t *testing.T) {
```
Comment (cbednarski) [inline builder/azure/arm/step_delete_resource_group_test.go]: For complex test cases I usually write the description in a comment instead, which is a bit easier to read / add context if needed.

**Comment by cbednarski** [comment]
LGTM!
